"""F8.3 — counter demo run + golden manifest reproducibility.

Drives ``specs/counter.md`` through the F8.1 CLI (``cmd_run`` +
``cmd_resume``) with deterministic args and asserts:

* The newly-produced manifest matches the committed
  ``tests/fixtures/counter_golden_manifest.json`` bit-for-bit on
  every ``content_hash`` — the F8.3 reproducibility AC.
* ``compare_to_manifest`` of the committed manifest is
  ``reproducible=True`` against a fresh store.
* The hash-chained audit log verifies clean end-to-end.
* The trace tree built from the run + resume tracer covers all
  seven stages (SPEC → PLAN → RTL → SYNTH → PHYSICAL → SIGNOFF →
  GDSII).

F10.1 routes the spec + plan through the real :class:`SpecIntakeAgent` +
:class:`PlannerAgent` over a stub :class:`CompletionBackend`. The
committed golden manifest is regenerated by re-running this demo
whenever the stub responses change.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from chip_agent.cli import RunArgs, cmd_resume, cmd_run
from chip_agent.design_state import ArtifactKind, Stage
from chip_agent.obs.audit_log import SqliteAuditLog
from chip_agent.obs.replay import RunManifest, compare_to_manifest
from chip_agent.obs.tracing import InMemoryTracer, SpanKind, build_trace_tree
from chip_agent.store.sqlite_store import SqliteArtifactStore
from tests._routing_stub import (
    StubBackend,
    make_routing_config,
    make_test_router,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
COUNTER_SPEC = REPO_ROOT / "specs" / "counter.md"
GOLDEN_MANIFEST_PATH = REPO_ROOT / "tests" / "fixtures" / "counter_golden_manifest.json"
GOLDEN_DESIGN_ID = "counter-demo-golden"
HMAC_KEY = b"f8-3-counter-demo-hmac-key"


@pytest.fixture
def routing_config(tmp_path: Path) -> Path:
    return make_routing_config(tmp_path)


@pytest.fixture
def patch_router(
    monkeypatch: pytest.MonkeyPatch,
    routing_config: Path,
) -> StubBackend:
    backend = StubBackend()
    router, _ = make_test_router(config_path=routing_config, backend=backend)
    monkeypatch.setattr("chip_agent.cli._resolve_router", lambda _args, *, settings: router)
    return backend


def _args(
    *,
    cmd: str,
    run_dir: Path,
    design_id: str,
    config_path: Path,
    spec_path: Path | None = None,
    name: str | None = None,
    tracer: InMemoryTracer | None = None,
) -> RunArgs:
    return RunArgs(
        cmd=cmd, spec_path=spec_path, name=name, run_dir=run_dir,
        design_id=design_id, hmac_key=HMAC_KEY, tracer=tracer,
        config_path=config_path,
    )


def _drive_demo(
    run_dir: Path,
    *,
    config_path: Path,
    design_id: str = GOLDEN_DESIGN_ID,
    tracer: InMemoryTracer | None = None,
) -> tuple[RunManifest, Path]:
    """Run the counter spec end-to-end through the CLI; return its manifest."""
    cmd_run(_args(
        cmd="run", run_dir=run_dir, design_id=design_id,
        spec_path=COUNTER_SPEC, name="counter", tracer=tracer,
        config_path=config_path,
    ))
    out = cmd_resume(_args(
        cmd="resume", run_dir=run_dir, design_id=design_id, tracer=tracer,
        config_path=config_path,
    ))
    return out.manifest, out.manifest_path


# --------------------------------------------------------------------------- #
# Fixture sanity — the committed golden exists and is well-formed.
# --------------------------------------------------------------------------- #
def test_committed_golden_manifest_exists_and_is_valid_json() -> None:
    assert GOLDEN_MANIFEST_PATH.exists(), (
        f"committed golden manifest missing at {GOLDEN_MANIFEST_PATH}"
    )
    payload = json.loads(GOLDEN_MANIFEST_PATH.read_text())
    assert payload["design_id"] == GOLDEN_DESIGN_ID
    assert payload["root_ref"]["kind"] == "gdsii"


# --------------------------------------------------------------------------- #
# F8.3 AC strand 1 — committed manifest reproduces against a fresh run.
# --------------------------------------------------------------------------- #
def test_counter_demo_run_reproduces_golden_manifest(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    fresh, _ = _drive_demo(tmp_path, config_path=routing_config)
    golden = RunManifest.model_validate_json(GOLDEN_MANIFEST_PATH.read_text())

    assert fresh.design_id == golden.design_id
    assert fresh.root_ref.content_hash == golden.root_ref.content_hash, (
        "GDS content_hash drifted from golden — stub templates changed?"
    )

    fresh_by_id = {f"{e.artifact_id}@v{e.version}": e for e in fresh.entries}
    golden_by_id = {f"{e.artifact_id}@v{e.version}": e for e in golden.entries}
    assert set(fresh_by_id) == set(golden_by_id), (
        f"manifest entries diverged from golden: "
        f"only in fresh={set(fresh_by_id) - set(golden_by_id)}, "
        f"only in golden={set(golden_by_id) - set(fresh_by_id)}"
    )
    for key, golden_entry in golden_by_id.items():
        fresh_entry = fresh_by_id[key]
        assert fresh_entry.content_hash == golden_entry.content_hash, (
            f"{key}: content_hash diverged from golden "
            f"(fresh={fresh_entry.content_hash}, golden={golden_entry.content_hash})"
        )
        assert fresh_entry.kind is golden_entry.kind


def test_counter_demo_compare_to_manifest_is_reproducible(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    """F7.3 ``compare_to_manifest`` verifies clean against the fresh store."""
    fresh, _ = _drive_demo(tmp_path, config_path=routing_config)
    with SqliteArtifactStore(
        db_path=tmp_path / "store.sqlite", content_dir=tmp_path / "content",
    ) as store:
        diff = compare_to_manifest(store, fresh)
    assert diff.reproducible, (
        f"fresh manifest does not verify against its own store: "
        f"missing={diff.missing!r}, mismatched={diff.mismatched!r}"
    )
    assert len(diff.matched) == 6  # spec, plan, rtl, netlist, layout, gds
    assert not diff.skipped         # no diagnosis artifacts in F8.3


def test_committed_golden_verifies_against_fresh_run_store(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    """The committed manifest must verify clean against a fresh run's store."""
    _drive_demo(tmp_path, config_path=routing_config)
    golden = RunManifest.model_validate_json(GOLDEN_MANIFEST_PATH.read_text())
    with SqliteArtifactStore(
        db_path=tmp_path / "store.sqlite", content_dir=tmp_path / "content",
    ) as store:
        diff = compare_to_manifest(store, golden)
    assert diff.reproducible, (
        f"committed golden does not verify against a fresh run: "
        f"missing={[e.artifact_id for e in diff.missing]!r}, "
        f"mismatched={[m.artifact_id for m in diff.mismatched]!r}"
    )


# --------------------------------------------------------------------------- #
# F8.3 AC strand 2 — audit log verifies clean.
# --------------------------------------------------------------------------- #
def test_counter_demo_audit_log_verifies_clean(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    _drive_demo(tmp_path, config_path=routing_config)
    audit = SqliteAuditLog(db_path=tmp_path / "audit.sqlite", hmac_key=HMAC_KEY)
    try:
        verdict = audit.verify(design_id=GOLDEN_DESIGN_ID)
    finally:
        audit.close()
    assert verdict.valid, f"audit log verify failed: {verdict.findings!r}"
    assert verdict.event_count >= 7  # ≥ 1 promotion per stage + decisions


def test_counter_demo_audit_log_records_promotion_for_every_stage(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    """Every stage up through PHYSICAL produces an ARTIFACT_PROMOTED event."""
    _drive_demo(tmp_path, config_path=routing_config)
    audit = SqliteAuditLog(db_path=tmp_path / "audit.sqlite", hmac_key=HMAC_KEY)
    try:
        events = list(audit.events(design_id=GOLDEN_DESIGN_ID))
    finally:
        audit.close()
    promoted_stages = {
        e.payload.get("stage")
        for e in events
        if e.event_type.value == "artifact_promoted"
    }
    assert {
        Stage.SPEC.value, Stage.PLAN.value, Stage.RTL.value,
        Stage.SYNTH.value, Stage.PHYSICAL.value, Stage.GDSII.value,
    } <= promoted_stages


# --------------------------------------------------------------------------- #
# F8.3 AC strand 3 — trace tree covers all spine stages.
# --------------------------------------------------------------------------- #
def test_counter_demo_trace_tree_covers_all_seven_stages(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    tracer = InMemoryTracer()
    _drive_demo(tmp_path, config_path=routing_config, tracer=tracer)

    roots = build_trace_tree(tracer.spans, design_id=GOLDEN_DESIGN_ID)
    assert roots, "expected at least one root span"

    stage_spans = [s for s in tracer.spans if s.kind is SpanKind.STAGE]
    stage_names = {s.name for s in stage_spans}
    # F19.7: every Stage value should appear as a STAGE span. The set
    # used to be hand-listed; it's now derived from the enum so adding
    # a new stage (CONTRACT / ORACLE / ASSERTIONS / ORACLE_VERIFICATION
    # in F19.7) extends the assertion automatically.
    expected = {stage.value for stage in Stage}
    assert stage_names == expected, (
        f"trace tree missing stages: {expected - stage_names!r}; "
        f"unexpected stages: {stage_names - expected!r}"
    )


def test_counter_demo_trace_tree_nests_stages_under_run_spans(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    """Every STAGE span has a RUN parent in the recorded forest."""
    tracer = InMemoryTracer()
    _drive_demo(tmp_path, config_path=routing_config, tracer=tracer)

    by_id = {s.span_id: s for s in tracer.spans}
    for span in tracer.spans:
        if span.kind is SpanKind.STAGE:
            assert span.parent_id is not None, f"stage {span.name!r} has no parent"
            parent = by_id[span.parent_id]
            assert parent.kind is SpanKind.RUN, (
                f"stage {span.name!r} parent is {parent.kind.value}, not RUN"
            )


# --------------------------------------------------------------------------- #
# Determinism — running the same demo twice gives identical content hashes.
# --------------------------------------------------------------------------- #
def test_counter_demo_two_runs_produce_identical_manifests(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    run_a = tmp_path / "a"
    run_b = tmp_path / "b"
    manifest_a, _ = _drive_demo(run_a, config_path=routing_config)
    manifest_b, _ = _drive_demo(run_b, config_path=routing_config)
    by_id_a = {(e.artifact_id, e.version): e.content_hash for e in manifest_a.entries}
    by_id_b = {(e.artifact_id, e.version): e.content_hash for e in manifest_b.entries}
    assert by_id_a == by_id_b


def test_counter_demo_changing_design_id_yields_distinct_artifacts(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    """Different ``design_id`` -> different artifact_ids AND content hashes.

    ``design_id`` is part of the content body (it's not in
    :data:`Artifact._NON_CONTENT_FIELDS`), so two runs of the same spec
    under different ids produce two independent artifact DAGs. This is
    the property the manifest comparator relies on.
    """
    manifest_g, _ = _drive_demo(
        tmp_path / "golden", config_path=routing_config, design_id=GOLDEN_DESIGN_ID,
    )
    manifest_x, _ = _drive_demo(
        tmp_path / "other", config_path=routing_config, design_id="counter-other",
    )
    hashes_g = {e.kind: e.content_hash for e in manifest_g.entries}
    hashes_x = {e.kind: e.content_hash for e in manifest_x.entries}
    assert hashes_g != hashes_x
    ids_g = {e.artifact_id for e in manifest_g.entries}
    ids_x = {e.artifact_id for e in manifest_x.entries}
    assert not (ids_g & ids_x)


# --------------------------------------------------------------------------- #
# F9.5 — TestbenchGenAgent populates the store with a cocotb testbench.
# --------------------------------------------------------------------------- #
def test_counter_demo_store_contains_cocotb_testbench(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    """The TB lands in the content store as the F19.8 differential harness.

    The TB doesn't currently appear in the run manifest — its ref lives
    in the simulation result's provenance, which is on the RTL stage's
    ``ss.results`` (not on the GDS lineage walk ``manifest_from_run``
    follows). The TB is still required to reproduce the run; this test
    pins that it's persisted with the right shape.

    Since F19.7 promotes per-module oracle + assertion heads before
    RTL, the F19.8 dispatch path triggers and the persisted TB is the
    deterministic differential harness — STIM/EXPECTED literals,
    ``getattr(dut, port)`` access, ``DIFF|...`` canonical assertion
    message. The legacy templated F9.5 TB now only fires when M19
    artifacts are missing (back-compat unit tests).
    """
    _drive_demo(tmp_path, config_path=routing_config)
    with SqliteArtifactStore(
        db_path=tmp_path / "store.sqlite", content_dir=tmp_path / "content",
    ) as store:
        tb = store.get_by_id(f"{GOLDEN_DESIGN_ID}.counter.tb")
        body = store.get_blob(tb.source).decode("utf-8")
    assert tb.kind is ArtifactKind.TESTBENCH
    assert tb.framework == "cocotb"
    assert tb.target_module == "counter"
    # F19.8 differential shape: embedded STIM/EXPECTED + canonical DIFF
    # token + the counter's clock and data ports referenced by name.
    assert "import cocotb" in body
    assert "STIM = " in body
    assert "EXPECTED = " in body
    assert "DIFF|cycle=" in body
    assert "'clk'" in body
    assert "'rst_n'" in body
    assert "'en'" in body
    assert "'q'" in body
    assert "assert " in body


def test_counter_demo_simulation_result_links_to_testbench(
    tmp_path: Path, routing_config: Path, patch_router: StubBackend,
) -> None:
    """The RTL stage's stored sim result has the TB on its lineage.

    This is the channel by which a replay reproduces the verification
    decision the RTL stage made — even though the manifest doesn't
    include the TB directly.
    """
    _drive_demo(tmp_path, config_path=routing_config)
    with SqliteArtifactStore(
        db_path=tmp_path / "store.sqlite", content_dir=tmp_path / "content",
    ) as store:
        sim = store.get_by_id(f"{GOLDEN_DESIGN_ID}.counter.sim")
        tb = store.get_by_id(f"{GOLDEN_DESIGN_ID}.counter.tb")
    tb_refs = [r for r in sim.provenance.inputs if r.kind is ArtifactKind.TESTBENCH]
    assert len(tb_refs) == 1
    assert tb_refs[0] == tb.ref()


@pytest.mark.parametrize("kind", [
    ArtifactKind.SPEC, ArtifactKind.PLAN, ArtifactKind.RTL,
    ArtifactKind.NETLIST, ArtifactKind.LAYOUT, ArtifactKind.GDSII,
])
def test_each_demo_artifact_kind_is_in_golden_manifest(kind: ArtifactKind) -> None:
    golden = RunManifest.model_validate_json(GOLDEN_MANIFEST_PATH.read_text())
    kinds = {e.kind for e in golden.entries}
    assert kind in kinds
