"""Ground-truth SPI vector testbench for spi_slave_regs (generated by spi_vector_tb).

Drives Mode-0 (CPOL=0, CPHA=0) 16-bit frames -- {RW, addr[6:0]} then a data
byte, MSB-first -- at clk/16, and checks each transaction against the
value published in the spec. `sclk` is driven as ordinary data, never as a
clock, mirroring the single-clock-domain constraint on the DUT.

Emits ``VEC|txn=N|signal=S|expected=E|actual=A`` on mismatch so
:func:`chip_agent.tools.trace.parse_failing_assertion` extracts structured
fields without fuzzy regex.
"""
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, Timer

SCLK_HALF = 8
# (rw, addr, data, expect_or_None, label)
PROGRAM = [(0, 0, 0, 90, 'reset value of ID @0x00'), (0, 1, 0, 1, 'reset value of VERSION @0x01'), (0, 2, 0, 0, 'reset value of CTRL @0x02'), (0, 16, 0, 0, 'reset value of SCRATCH @0x10'), (0, 0, 0, 90, 'read 0x00'), (0, 1, 0, 1, 'read 0x01'), (1, 16, 165, None, 'write 0xA5 -> 0x10'), (0, 16, 0, 165, 'read 0x10'), (1, 19, 60, None, 'write 0x3C -> 0x13'), (0, 19, 0, 60, 'read 0x13'), (0, 16, 0, 165, 'read 0x10'), (1, 2, 119, None, 'write 0x77 -> 0x02'), (0, 2, 0, 119, 'read 0x02'), (1, 17, 15, None, 'write 0x0F -> 0x11'), (0, 17, 0, 15, 'read 0x11'), (0, 126, 0, 0, 'read 0x7E'), (0, 19, 0, 60, 'read 0x13')]


async def _frame(dut, cmd, data):
    """Drive one 16-bit Mode-0 frame; return the byte sampled during byte 1."""
    word = ((cmd & 0xFF) << 8) | (data & 0xFF)
    dut.cs_n.value = 0
    await ClockCycles(dut.clk, SCLK_HALF)
    rx = 0
    for i in range(15, -1, -1):
        # Master presents MOSI while SCLK is low ...
        dut.mosi.value = (word >> i) & 1
        await ClockCycles(dut.clk, SCLK_HALF)
        # ... slave samples MOSI on the rising edge; master samples MISO there
        # too (the slave drove it on the preceding falling edge).
        dut.sclk.value = 1
        await Timer(1, units="ns")
        rx = ((rx << 1) | (int(dut.miso.value) & 1)) & 0xFFFF
        await ClockCycles(dut.clk, SCLK_HALF)
        dut.sclk.value = 0
    await ClockCycles(dut.clk, SCLK_HALF)
    dut.cs_n.value = 1
    await ClockCycles(dut.clk, SCLK_HALF)
    return rx & 0xFF


@cocotb.test()
async def test_spi_slave_regs_spi_vectors(dut):
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())

    # Reset once, before the program: the register-map reads assert reset
    # values, and later writes are expected to persist across transactions.
    dut.rst_n.value = 0
    dut.sclk.value = 0
    dut.cs_n.value = 1
    dut.mosi.value = 0
    await ClockCycles(dut.clk, 4)
    dut.rst_n.value = 1
    await ClockCycles(dut.clk, 4)

    for idx, (rw, addr, data, expect, label) in enumerate(PROGRAM):
        cmd = ((rw & 1) << 7) | (addr & 0x7F)
        got = await _frame(dut, cmd, data)
        assert int(dut.done.value) == 1, (
            f"VEC|txn={idx}|signal=done|expected=1|actual=0 "
            f"({label}: done never asserted after a well-formed 16-bit frame)"
        )

        if expect is not None:
            assert got == expect, (
                f"VEC|txn={idx}|signal=miso|"
                f"expected={expect}|actual={got} "
                f"({label}: expected 0x{expect:02X}, got 0x{got:02X})"
            )
