/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module present80(clk, rst_n, start, plaintext, key, ciphertext, done);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input [63:0] plaintext;
  wire [63:0] plaintext;
  input [79:0] key;
  wire [79:0] key;
  output [63:0] ciphertext;
  reg [63:0] ciphertext;
  output done;
  reg done;
  wire _0000_;
  wire [79:0] _0001_;
  wire [4:0] _0002_;
  wire _0003_;
  wire [63:0] _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire [63:0] after_xor;
  wire [79:0] \keySchedule$func$present80.v:121$24.k ;
  wire [79:0] \keySchedule$func$present80.v:121$24.k1 ;
  wire [4:0] \keySchedule$func$present80.v:121$24.round_cnt ;
  wire [3:0] \keySchedule$func$present80.v:121$24.s_out ;
  reg [79:0] key_reg;
  wire [79:0] next_key;
  wire [31:0] \pLayer$func$present80.v:118$23.i ;
  wire [63:0] \pLayer$func$present80.v:118$23.result ;
  wire [63:0] \pLayer$func$present80.v:118$23.state ;
  reg [4:0] round_cnt;
  reg running;
  wire [31:0] \sLayer$func$present80.v:115$6.i ;
  wire [63:0] \sLayer$func$present80.v:115$6.result ;
  wire [63:0] \sLayer$func$present80.v:115$6.state ;
  wire [3:0] \sbox$func$present80.v:51$10.x ;
  wire [3:0] \sbox$func$present80.v:51$11.x ;
  wire [3:0] \sbox$func$present80.v:51$12.x ;
  wire [3:0] \sbox$func$present80.v:51$13.x ;
  wire [3:0] \sbox$func$present80.v:51$14.x ;
  wire [3:0] \sbox$func$present80.v:51$15.x ;
  wire [3:0] \sbox$func$present80.v:51$16.x ;
  wire [3:0] \sbox$func$present80.v:51$17.x ;
  wire [3:0] \sbox$func$present80.v:51$18.x ;
  wire [3:0] \sbox$func$present80.v:51$19.x ;
  wire [3:0] \sbox$func$present80.v:51$20.x ;
  wire [3:0] \sbox$func$present80.v:51$21.x ;
  wire [3:0] \sbox$func$present80.v:51$22.x ;
  wire [3:0] \sbox$func$present80.v:51$7.x ;
  wire [3:0] \sbox$func$present80.v:51$8.x ;
  wire [3:0] \sbox$func$present80.v:51$9.x ;
  wire [3:0] \sbox$func$present80.v:87$25.x ;
  reg [63:0] state_reg;
  assign after_xor[25] = key_reg[41] ^ state_reg[25];
  assign _0059_ = ~(key_reg[42] ^ state_reg[26]);
  assign after_xor[26] = ~_0059_;
  assign after_xor[24] = key_reg[40] ^ state_reg[24];
  assign _0060_ = ~after_xor[24];
  assign after_xor[27] = key_reg[43] ^ state_reg[27];
  assign after_xor[28] = key_reg[44] ^ state_reg[28];
  assign _0061_ = ~after_xor[28];
  assign after_xor[0] = key_reg[16] ^ state_reg[0];
  assign after_xor[1] = key_reg[17] ^ state_reg[1];
  assign after_xor[29] = key_reg[45] ^ state_reg[29];
  assign after_xor[17] = key_reg[33] ^ state_reg[17];
  assign _0062_ = ~(key_reg[46] ^ state_reg[30]);
  assign after_xor[30] = ~_0062_;
  assign after_xor[31] = key_reg[47] ^ state_reg[31];
  assign after_xor[32] = key_reg[48] ^ state_reg[32];
  assign _0063_ = ~after_xor[32];
  assign after_xor[33] = key_reg[49] ^ state_reg[33];
  assign _0064_ = ~(key_reg[34] ^ state_reg[18]);
  assign after_xor[18] = ~_0064_;
  assign after_xor[16] = key_reg[32] ^ state_reg[16];
  assign _0065_ = ~after_xor[16];
  assign after_xor[34] = key_reg[50] ^ state_reg[34];
  assign after_xor[35] = key_reg[51] ^ state_reg[35];
  assign after_xor[36] = key_reg[52] ^ state_reg[36];
  assign after_xor[2] = key_reg[18] ^ state_reg[2];
  assign after_xor[37] = key_reg[53] ^ state_reg[37];
  assign after_xor[38] = key_reg[54] ^ state_reg[38];
  assign after_xor[39] = key_reg[55] ^ state_reg[39];
  assign after_xor[40] = key_reg[56] ^ state_reg[40];
  assign _0066_ = ~after_xor[40];
  assign after_xor[41] = key_reg[57] ^ state_reg[41];
  assign after_xor[19] = key_reg[35] ^ state_reg[19];
  assign after_xor[3] = key_reg[19] ^ state_reg[3];
  assign _0067_ = ~(key_reg[58] ^ state_reg[42]);
  assign after_xor[42] = ~_0067_;
  assign after_xor[43] = key_reg[59] ^ state_reg[43];
  assign after_xor[44] = key_reg[60] ^ state_reg[44];
  assign _0068_ = ~after_xor[44];
  assign after_xor[4] = key_reg[20] ^ state_reg[4];
  assign _0069_ = ~after_xor[4];
  assign after_xor[45] = key_reg[61] ^ state_reg[45];
  assign _0070_ = ~(key_reg[62] ^ state_reg[46]);
  assign after_xor[46] = ~_0070_;
  assign after_xor[47] = key_reg[63] ^ state_reg[47];
  assign after_xor[48] = key_reg[64] ^ state_reg[48];
  assign _0071_ = ~after_xor[48];
  assign after_xor[5] = key_reg[21] ^ state_reg[5];
  assign after_xor[60] = key_reg[76] ^ state_reg[60];
  assign after_xor[61] = key_reg[77] ^ state_reg[61];
  assign after_xor[59] = key_reg[75] ^ state_reg[59];
  assign after_xor[56] = key_reg[72] ^ state_reg[56];
  assign _0072_ = ~after_xor[56];
  assign after_xor[57] = key_reg[73] ^ state_reg[57];
  assign _0073_ = ~(after_xor[56] & after_xor[57]);
  assign _0074_ = after_xor[56] | after_xor[57];
  assign _0075_ = _0073_ & _0074_;
  assign _0076_ = ~(key_reg[74] ^ state_reg[58]);
  assign after_xor[58] = ~_0076_;
  assign _0077_ = after_xor[56] | _0076_;
  assign _0078_ = _0075_ & _0077_;
  assign _0079_ = after_xor[59] | _0078_;
  assign _0080_ = after_xor[59] & _0076_;
  assign _0081_ = ~(_0074_ & _0080_);
  assign _0082_ = ~(_0079_ & _0081_);
  assign _0004_[62] = start ? plaintext[62] : _0082_;
  assign after_xor[55] = key_reg[71] ^ state_reg[55];
  assign after_xor[52] = key_reg[68] ^ state_reg[52];
  assign _0083_ = ~after_xor[52];
  assign after_xor[53] = key_reg[69] ^ state_reg[53];
  assign _0084_ = ~(after_xor[52] & after_xor[53]);
  assign _0085_ = after_xor[52] | after_xor[53];
  assign _0086_ = _0084_ & _0085_;
  assign _0087_ = ~(key_reg[70] ^ state_reg[54]);
  assign after_xor[54] = ~_0087_;
  assign _0088_ = after_xor[52] | _0087_;
  assign _0089_ = _0086_ & _0088_;
  assign _0090_ = after_xor[55] | _0089_;
  assign _0091_ = after_xor[55] & _0087_;
  assign _0092_ = ~(_0085_ & _0091_);
  assign _0093_ = ~(_0090_ & _0092_);
  assign _0004_[61] = start ? plaintext[61] : _0093_;
  assign after_xor[51] = key_reg[67] ^ state_reg[51];
  assign after_xor[49] = key_reg[65] ^ state_reg[49];
  assign _0094_ = ~(after_xor[48] & after_xor[49]);
  assign _0095_ = after_xor[48] | after_xor[49];
  assign _0096_ = _0094_ & _0095_;
  assign _0097_ = ~(key_reg[66] ^ state_reg[50]);
  assign after_xor[50] = ~_0097_;
  assign _0098_ = after_xor[48] | _0097_;
  assign _0099_ = _0096_ & _0098_;
  assign _0100_ = after_xor[51] | _0099_;
  assign _0101_ = after_xor[51] & _0097_;
  assign _0102_ = ~(_0095_ & _0101_);
  assign _0103_ = ~(_0100_ & _0102_);
  assign _0004_[60] = start ? plaintext[60] : _0103_;
  assign _0104_ = ~(after_xor[44] & after_xor[45]);
  assign _0105_ = after_xor[44] | after_xor[45];
  assign _0106_ = _0104_ & _0105_;
  assign _0107_ = after_xor[44] | _0070_;
  assign _0108_ = _0106_ & _0107_;
  assign _0109_ = after_xor[47] | _0108_;
  assign _0110_ = _0070_ & after_xor[47];
  assign _0111_ = ~(_0105_ & _0110_);
  assign _0112_ = ~(_0109_ & _0111_);
  assign _0004_[59] = start ? plaintext[59] : _0112_;
  assign _0113_ = ~(after_xor[40] & after_xor[41]);
  assign _0114_ = after_xor[40] | after_xor[41];
  assign _0115_ = _0113_ & _0114_;
  assign _0116_ = after_xor[40] | _0067_;
  assign _0117_ = _0115_ & _0116_;
  assign _0118_ = after_xor[43] | _0117_;
  assign _0119_ = _0067_ & after_xor[43];
  assign _0120_ = ~(_0114_ & _0119_);
  assign _0121_ = ~(_0118_ & _0120_);
  assign _0004_[58] = start ? plaintext[58] : _0121_;
  assign _0122_ = ~(after_xor[36] & after_xor[37]);
  assign _0123_ = after_xor[36] | after_xor[37];
  assign _0124_ = ~(after_xor[36] ^ after_xor[37]);
  assign _0125_ = after_xor[36] | ~(after_xor[38]);
  assign _0126_ = _0125_ & ~(_0124_);
  assign _0127_ = after_xor[39] | _0126_;
  assign _0128_ = after_xor[39] & ~(after_xor[38]);
  assign _0129_ = ~(_0123_ & _0128_);
  assign _0130_ = ~(_0127_ & _0129_);
  assign _0004_[57] = start ? plaintext[57] : _0130_;
  assign _0131_ = ~(after_xor[32] & after_xor[33]);
  assign _0132_ = after_xor[32] | after_xor[33];
  assign _0133_ = _0131_ & _0132_;
  assign _0134_ = after_xor[32] | ~(after_xor[34]);
  assign _0135_ = _0133_ & _0134_;
  assign _0136_ = after_xor[35] | _0135_;
  assign _0137_ = after_xor[35] & ~(after_xor[34]);
  assign _0138_ = ~(_0132_ & _0137_);
  assign _0139_ = ~(_0136_ & _0138_);
  assign _0004_[56] = start ? plaintext[56] : _0139_;
  assign _0140_ = ~(after_xor[28] & after_xor[29]);
  assign _0141_ = after_xor[28] | after_xor[29];
  assign _0142_ = _0140_ & _0141_;
  assign _0143_ = after_xor[28] | _0062_;
  assign _0144_ = _0142_ & _0143_;
  assign _0145_ = after_xor[31] | _0144_;
  assign _0146_ = _0062_ & after_xor[31];
  assign _0147_ = ~(_0141_ & _0146_);
  assign _0148_ = ~(_0145_ & _0147_);
  assign _0004_[55] = start ? plaintext[55] : _0148_;
  assign _0149_ = after_xor[25] | after_xor[24];
  assign _0150_ = _0059_ & _0149_;
  assign _0151_ = ~(after_xor[25] & after_xor[24]);
  assign _0152_ = _0149_ & _0151_;
  assign _0153_ = ~(after_xor[25] & after_xor[26]);
  assign _0154_ = ~(_0152_ & _0153_);
  assign _0155_ = after_xor[27] ? _0150_ : _0154_;
  assign _0004_[54] = start ? plaintext[54] : _0155_;
  assign after_xor[23] = key_reg[39] ^ state_reg[23];
  assign after_xor[20] = key_reg[36] ^ state_reg[20];
  assign after_xor[21] = key_reg[37] ^ state_reg[21];
  assign _0156_ = ~(after_xor[20] & after_xor[21]);
  assign _0157_ = after_xor[20] | after_xor[21];
  assign _0158_ = ~(after_xor[20] ^ after_xor[21]);
  assign after_xor[22] = state_reg[22] ^ key_reg[38];
  assign _0159_ = after_xor[20] | ~(after_xor[22]);
  assign _0160_ = _0159_ & ~(_0158_);
  assign _0161_ = after_xor[23] | _0160_;
  assign _0162_ = after_xor[23] & ~(after_xor[22]);
  assign _0163_ = ~(_0157_ & _0162_);
  assign _0164_ = ~(_0161_ & _0163_);
  assign _0004_[53] = start ? plaintext[53] : _0164_;
  assign _0165_ = after_xor[17] | after_xor[16];
  assign _0166_ = _0064_ & _0165_;
  assign _0167_ = ~(after_xor[17] & after_xor[16]);
  assign _0168_ = _0165_ & _0167_;
  assign _0169_ = ~(after_xor[17] & after_xor[18]);
  assign _0170_ = ~(_0168_ & _0169_);
  assign _0171_ = after_xor[19] ? _0166_ : _0170_;
  assign _0004_[52] = start ? plaintext[52] : _0171_;
  assign after_xor[15] = key_reg[31] ^ state_reg[15];
  assign after_xor[12] = key_reg[28] ^ state_reg[12];
  assign _0172_ = ~after_xor[12];
  assign after_xor[13] = key_reg[29] ^ state_reg[13];
  assign _0173_ = ~(after_xor[12] & after_xor[13]);
  assign _0174_ = after_xor[12] | after_xor[13];
  assign _0175_ = _0173_ & _0174_;
  assign after_xor[14] = key_reg[30] ^ state_reg[14];
  assign _0176_ = after_xor[12] | ~(after_xor[14]);
  assign _0177_ = _0175_ & _0176_;
  assign _0178_ = after_xor[15] | _0177_;
  assign _0179_ = after_xor[15] & ~(after_xor[14]);
  assign _0180_ = ~(_0174_ & _0179_);
  assign _0181_ = ~(_0178_ & _0180_);
  assign _0004_[51] = start ? plaintext[51] : _0181_;
  assign after_xor[11] = key_reg[27] ^ state_reg[11];
  assign after_xor[8] = key_reg[24] ^ state_reg[8];
  assign after_xor[9] = key_reg[25] ^ state_reg[9];
  assign _0182_ = ~(after_xor[8] & after_xor[9]);
  assign _0183_ = after_xor[8] | after_xor[9];
  assign _0184_ = ~(after_xor[8] ^ after_xor[9]);
  assign after_xor[10] = key_reg[26] ^ state_reg[10];
  assign _0185_ = after_xor[8] | ~(after_xor[10]);
  assign _0186_ = _0185_ & ~(_0184_);
  assign _0187_ = after_xor[11] | _0186_;
  assign _0188_ = after_xor[11] & ~(after_xor[10]);
  assign _0189_ = ~(_0183_ & _0188_);
  assign _0190_ = ~(_0187_ & _0189_);
  assign _0004_[50] = start ? plaintext[50] : _0190_;
  assign after_xor[7] = key_reg[23] ^ state_reg[7];
  assign _0191_ = ~(after_xor[4] & after_xor[5]);
  assign _0192_ = after_xor[4] | after_xor[5];
  assign _0193_ = _0191_ & _0192_;
  assign _0194_ = ~(key_reg[22] ^ state_reg[6]);
  assign after_xor[6] = ~_0194_;
  assign _0195_ = after_xor[4] | _0194_;
  assign _0196_ = _0193_ & _0195_;
  assign _0197_ = after_xor[7] | _0196_;
  assign _0198_ = after_xor[7] & _0194_;
  assign _0199_ = ~(_0192_ & _0198_);
  assign _0200_ = ~(_0197_ & _0199_);
  assign _0004_[49] = start ? plaintext[49] : _0200_;
  assign _0201_ = ~(after_xor[0] & after_xor[1]);
  assign _0202_ = after_xor[0] | after_xor[1];
  assign _0203_ = ~(after_xor[0] ^ after_xor[1]);
  assign _0204_ = after_xor[0] | ~(after_xor[2]);
  assign _0205_ = _0204_ & ~(_0203_);
  assign _0206_ = after_xor[3] | _0205_;
  assign _0207_ = after_xor[3] & ~(after_xor[2]);
  assign _0208_ = ~(_0202_ & _0207_);
  assign _0209_ = ~(_0206_ & _0208_);
  assign _0004_[48] = start ? plaintext[48] : _0209_;
  assign _0210_ = ~(key_reg[78] ^ state_reg[62]);
  assign after_xor[62] = ~_0210_;
  assign _0211_ = ~(after_xor[60] & after_xor[61]);
  assign _0212_ = ~(after_xor[60] & _0210_);
  assign after_xor[63] = key_reg[79] ^ state_reg[63];
  assign _0213_ = ~(_0212_ & after_xor[63]);
  assign _0214_ = _0213_ ? _0211_ : after_xor[61];
  assign _0215_ = ~(_0210_ ^ _0214_);
  assign _0004_[47] = start ? plaintext[47] : _0215_;
  assign _0216_ = ~(after_xor[56] & _0076_);
  assign _0217_ = ~(after_xor[59] & _0216_);
  assign _0218_ = _0217_ ? _0073_ : after_xor[57];
  assign _0219_ = ~(_0076_ ^ _0218_);
  assign _0004_[46] = start ? plaintext[46] : _0219_;
  assign _0220_ = ~(after_xor[52] & _0087_);
  assign _0221_ = ~(after_xor[55] & _0220_);
  assign _0222_ = _0221_ ? _0084_ : after_xor[53];
  assign _0223_ = ~(_0087_ ^ _0222_);
  assign _0004_[45] = start ? plaintext[45] : _0223_;
  assign _0224_ = ~(after_xor[48] & _0097_);
  assign _0225_ = ~(after_xor[51] & _0224_);
  assign _0226_ = _0225_ ? _0094_ : after_xor[49];
  assign _0227_ = ~(_0097_ ^ _0226_);
  assign _0004_[44] = start ? plaintext[44] : _0227_;
  assign _0228_ = ~(after_xor[44] & _0070_);
  assign _0229_ = ~(after_xor[47] & _0228_);
  assign _0230_ = _0229_ ? _0104_ : after_xor[45];
  assign _0231_ = ~(_0070_ ^ _0230_);
  assign _0004_[43] = start ? plaintext[43] : _0231_;
  assign _0232_ = ~(after_xor[40] & _0067_);
  assign _0233_ = ~(after_xor[43] & _0232_);
  assign _0234_ = _0233_ ? _0113_ : after_xor[41];
  assign _0235_ = ~(_0067_ ^ _0234_);
  assign _0004_[42] = start ? plaintext[42] : _0235_;
  assign _0236_ = after_xor[38] | ~(after_xor[36]);
  assign _0237_ = ~(after_xor[39] & _0236_);
  assign _0238_ = _0237_ ? _0122_ : after_xor[37];
  assign _0239_ = after_xor[38] ^ _0238_;
  assign _0004_[41] = start ? plaintext[41] : _0239_;
  assign _0240_ = after_xor[34] | ~(after_xor[32]);
  assign _0241_ = ~(after_xor[35] & _0240_);
  assign _0242_ = _0241_ ? _0131_ : after_xor[33];
  assign _0243_ = after_xor[34] ^ _0242_;
  assign _0004_[40] = start ? plaintext[40] : _0243_;
  assign _0244_ = ~(after_xor[28] & _0062_);
  assign _0245_ = ~(after_xor[31] & _0244_);
  assign _0246_ = _0245_ ? _0140_ : after_xor[29];
  assign _0247_ = ~(_0062_ ^ _0246_);
  assign _0004_[39] = start ? plaintext[39] : _0247_;
  assign _0248_ = ~(_0059_ & after_xor[24]);
  assign _0249_ = ~(after_xor[27] & _0248_);
  assign _0250_ = _0249_ ? _0151_ : after_xor[25];
  assign _0251_ = ~(_0059_ ^ _0250_);
  assign _0004_[38] = start ? plaintext[38] : _0251_;
  assign _0252_ = after_xor[22] | ~(after_xor[20]);
  assign _0253_ = ~(after_xor[23] & _0252_);
  assign _0254_ = _0253_ ? _0156_ : after_xor[21];
  assign _0255_ = after_xor[22] ^ _0254_;
  assign _0004_[37] = start ? plaintext[37] : _0255_;
  assign _0256_ = ~(_0064_ & after_xor[16]);
  assign _0257_ = ~(after_xor[19] & _0256_);
  assign _0258_ = _0257_ ? _0167_ : after_xor[17];
  assign _0259_ = ~(_0064_ ^ _0258_);
  assign _0004_[36] = start ? plaintext[36] : _0259_;
  assign _0260_ = after_xor[14] | ~(after_xor[12]);
  assign _0261_ = ~(after_xor[15] & _0260_);
  assign _0262_ = _0261_ ? _0173_ : after_xor[13];
  assign _0263_ = after_xor[14] ^ _0262_;
  assign _0004_[35] = start ? plaintext[35] : _0263_;
  assign _0264_ = after_xor[10] | ~(after_xor[8]);
  assign _0265_ = ~(after_xor[11] & _0264_);
  assign _0266_ = _0265_ ? _0182_ : after_xor[9];
  assign _0267_ = after_xor[10] ^ _0266_;
  assign _0004_[34] = start ? plaintext[34] : _0267_;
  assign _0268_ = ~(after_xor[4] & _0194_);
  assign _0269_ = ~(after_xor[7] & _0268_);
  assign _0270_ = _0269_ ? _0191_ : after_xor[5];
  assign _0271_ = ~(_0194_ ^ _0270_);
  assign _0004_[33] = start ? plaintext[33] : _0271_;
  assign _0272_ = after_xor[2] | ~(after_xor[0]);
  assign _0273_ = ~(after_xor[3] & _0272_);
  assign _0274_ = _0273_ ? _0201_ : after_xor[1];
  assign _0275_ = after_xor[2] ^ _0274_;
  assign _0004_[32] = start ? plaintext[32] : _0275_;
  assign _0276_ = plaintext[31] | ~(start);
  assign _0277_ = after_xor[60] & ~(_0210_);
  assign _0278_ = _0210_ ? _0211_ : after_xor[60];
  assign _0279_ = ~(after_xor[63] & _0278_);
  assign _0280_ = after_xor[61] & ~(after_xor[63]);
  assign _0281_ = _0280_ & ~(_0277_);
  assign _0282_ = ~(start | _0281_);
  assign _0283_ = ~(_0279_ & _0282_);
  assign _0004_[31] = _0276_ & _0283_;
  assign _0284_ = after_xor[56] & ~(_0076_);
  assign _0285_ = _0076_ ? _0073_ : after_xor[56];
  assign _0286_ = ~(after_xor[59] & _0285_);
  assign _0287_ = after_xor[59] | ~(after_xor[57]);
  assign _0288_ = _0284_ | _0287_;
  assign _0289_ = ~(_0286_ & _0288_);
  assign _0004_[30] = start ? plaintext[30] : _0289_;
  assign _0290_ = after_xor[52] & ~(_0087_);
  assign _0291_ = _0087_ ? _0084_ : after_xor[52];
  assign _0292_ = ~(after_xor[55] & _0291_);
  assign _0293_ = after_xor[55] | ~(after_xor[53]);
  assign _0294_ = _0290_ | _0293_;
  assign _0295_ = ~(_0292_ & _0294_);
  assign _0004_[29] = start ? plaintext[29] : _0295_;
  assign _0296_ = after_xor[48] & ~(_0097_);
  assign _0297_ = _0097_ ? _0094_ : after_xor[48];
  assign _0298_ = ~(after_xor[51] & _0297_);
  assign _0299_ = after_xor[51] | ~(after_xor[49]);
  assign _0300_ = _0296_ | _0299_;
  assign _0301_ = ~(_0298_ & _0300_);
  assign _0004_[28] = start ? plaintext[28] : _0301_;
  assign _0302_ = after_xor[44] & ~(_0070_);
  assign _0303_ = _0070_ ? _0104_ : after_xor[44];
  assign _0304_ = ~(after_xor[47] & _0303_);
  assign _0305_ = after_xor[47] | ~(after_xor[45]);
  assign _0306_ = _0302_ | _0305_;
  assign _0307_ = ~(_0304_ & _0306_);
  assign _0004_[27] = start ? plaintext[27] : _0307_;
  assign _0308_ = after_xor[40] & ~(_0067_);
  assign _0309_ = _0067_ ? _0113_ : after_xor[40];
  assign _0310_ = ~(after_xor[43] & _0309_);
  assign _0311_ = after_xor[43] | ~(after_xor[41]);
  assign _0312_ = _0308_ | _0311_;
  assign _0313_ = ~(_0310_ & _0312_);
  assign _0004_[26] = start ? plaintext[26] : _0313_;
  assign _0314_ = ~(after_xor[36] & after_xor[38]);
  assign _0315_ = after_xor[38] ? after_xor[36] : _0122_;
  assign _0316_ = ~(after_xor[39] & _0315_);
  assign _0317_ = after_xor[37] & ~(after_xor[39]);
  assign _0318_ = ~(_0314_ & _0317_);
  assign _0319_ = ~(_0316_ & _0318_);
  assign _0004_[25] = start ? plaintext[25] : _0319_;
  assign _0320_ = ~(after_xor[32] & after_xor[34]);
  assign _0321_ = after_xor[34] ? after_xor[32] : _0131_;
  assign _0322_ = ~(after_xor[35] & _0321_);
  assign _0323_ = after_xor[33] & ~(after_xor[35]);
  assign _0324_ = ~(_0320_ & _0323_);
  assign _0325_ = ~(_0322_ & _0324_);
  assign _0004_[24] = start ? plaintext[24] : _0325_;
  assign _0326_ = after_xor[28] & ~(_0062_);
  assign _0327_ = _0062_ ? _0140_ : after_xor[28];
  assign _0328_ = ~(after_xor[31] & _0327_);
  assign _0329_ = after_xor[31] | ~(after_xor[29]);
  assign _0330_ = _0326_ | _0329_;
  assign _0331_ = ~(_0328_ & _0330_);
  assign _0004_[23] = start ? plaintext[23] : _0331_;
  assign _0332_ = ~(after_xor[26] & after_xor[24]);
  assign _0333_ = _0059_ ? _0151_ : after_xor[24];
  assign _0334_ = ~(after_xor[27] & _0333_);
  assign _0335_ = after_xor[25] & ~(after_xor[27]);
  assign _0336_ = ~(_0332_ & _0335_);
  assign _0337_ = ~(_0334_ & _0336_);
  assign _0004_[22] = start ? plaintext[22] : _0337_;
  assign _0338_ = ~(after_xor[20] & after_xor[22]);
  assign _0339_ = after_xor[22] ? after_xor[20] : _0156_;
  assign _0340_ = ~(after_xor[23] & _0339_);
  assign _0341_ = after_xor[21] & ~(after_xor[23]);
  assign _0342_ = ~(_0338_ & _0341_);
  assign _0343_ = ~(_0340_ & _0342_);
  assign _0004_[21] = start ? plaintext[21] : _0343_;
  assign _0344_ = ~(after_xor[18] & after_xor[16]);
  assign _0345_ = _0064_ ? _0167_ : after_xor[16];
  assign _0346_ = ~(after_xor[19] & _0345_);
  assign _0347_ = after_xor[17] & ~(after_xor[19]);
  assign _0348_ = ~(_0344_ & _0347_);
  assign _0349_ = ~(_0346_ & _0348_);
  assign _0004_[20] = start ? plaintext[20] : _0349_;
  assign _0350_ = ~(after_xor[12] & after_xor[14]);
  assign _0351_ = after_xor[14] ? after_xor[12] : _0173_;
  assign _0352_ = ~(after_xor[15] & _0351_);
  assign _0353_ = after_xor[13] & ~(after_xor[15]);
  assign _0354_ = ~(_0350_ & _0353_);
  assign _0355_ = ~(_0352_ & _0354_);
  assign _0004_[19] = start ? plaintext[19] : _0355_;
  assign _0356_ = ~(after_xor[8] & after_xor[10]);
  assign _0357_ = after_xor[10] ? after_xor[8] : _0182_;
  assign _0358_ = ~(after_xor[11] & _0357_);
  assign _0359_ = after_xor[9] & ~(after_xor[11]);
  assign _0360_ = ~(_0356_ & _0359_);
  assign _0361_ = ~(_0358_ & _0360_);
  assign _0004_[18] = start ? plaintext[18] : _0361_;
  assign _0362_ = after_xor[4] & ~(_0194_);
  assign _0363_ = _0194_ ? _0191_ : after_xor[4];
  assign _0364_ = ~(after_xor[7] & _0363_);
  assign _0365_ = after_xor[7] | ~(after_xor[5]);
  assign _0366_ = _0362_ | _0365_;
  assign _0367_ = ~(_0364_ & _0366_);
  assign _0004_[17] = start ? plaintext[17] : _0367_;
  assign _0368_ = ~(after_xor[0] & after_xor[2]);
  assign _0369_ = after_xor[2] ? after_xor[0] : _0201_;
  assign _0370_ = ~(after_xor[3] & _0369_);
  assign _0371_ = after_xor[1] & ~(after_xor[3]);
  assign _0372_ = ~(_0368_ & _0371_);
  assign _0373_ = ~(_0370_ & _0372_);
  assign _0004_[16] = start ? plaintext[16] : _0373_;
  assign _0374_ = after_xor[61] & ~(after_xor[60]);
  assign _0375_ = after_xor[61] | ~(after_xor[60]);
  assign _0376_ = ~(after_xor[62] & _0375_);
  assign _0377_ = _0374_ | _0376_;
  assign _0378_ = _0212_ & _0377_;
  assign _0379_ = ~(after_xor[63] ^ _0378_);
  assign _0004_[15] = start ? plaintext[15] : _0379_;
  assign _0380_ = _0076_ ? _0072_ : _0075_;
  assign _0381_ = ~(after_xor[59] ^ _0380_);
  assign _0004_[14] = start ? plaintext[14] : _0381_;
  assign _0382_ = _0087_ ? _0083_ : _0086_;
  assign _0383_ = ~(after_xor[55] ^ _0382_);
  assign _0004_[13] = start ? plaintext[13] : _0383_;
  assign _0384_ = _0097_ ? _0071_ : _0096_;
  assign _0385_ = ~(after_xor[51] ^ _0384_);
  assign _0004_[12] = start ? plaintext[12] : _0385_;
  assign _0386_ = _0070_ ? _0068_ : _0106_;
  assign _0387_ = ~(after_xor[47] ^ _0386_);
  assign _0004_[11] = start ? plaintext[11] : _0387_;
  assign _0388_ = _0067_ ? _0066_ : _0115_;
  assign _0389_ = ~(after_xor[43] ^ _0388_);
  assign _0004_[10] = start ? plaintext[10] : _0389_;
  assign _0390_ = plaintext[9] | ~(start);
  assign _0391_ = ~(after_xor[38] & _0124_);
  assign _0392_ = after_xor[38] ? _0124_ : after_xor[36];
  assign _0393_ = after_xor[39] | ~(_0392_);
  assign _0394_ = _0391_ & ~(_0237_);
  assign _0395_ = ~(start | _0394_);
  assign _0396_ = ~(_0393_ & _0395_);
  assign _0004_[9] = _0390_ & _0396_;
  assign _0397_ = after_xor[34] ? _0133_ : _0063_;
  assign _0398_ = ~(after_xor[35] ^ _0397_);
  assign _0004_[8] = start ? plaintext[8] : _0398_;
  assign _0399_ = _0062_ ? _0061_ : _0142_;
  assign _0400_ = ~(after_xor[31] ^ _0399_);
  assign _0004_[7] = start ? plaintext[7] : _0400_;
  assign _0401_ = _0059_ ? _0060_ : _0152_;
  assign _0402_ = ~(after_xor[27] ^ _0401_);
  assign _0004_[6] = start ? plaintext[6] : _0402_;
  assign _0403_ = plaintext[5] | ~(start);
  assign _0404_ = ~(_0158_ & after_xor[22]);
  assign _0405_ = after_xor[22] ? _0158_ : after_xor[20];
  assign _0406_ = after_xor[23] | ~(_0405_);
  assign _0407_ = _0404_ & ~(_0253_);
  assign _0408_ = ~(start | _0407_);
  assign _0409_ = ~(_0406_ & _0408_);
  assign _0004_[5] = _0403_ & _0409_;
  assign _0410_ = _0064_ ? _0065_ : _0168_;
  assign _0411_ = ~(after_xor[19] ^ _0410_);
  assign _0004_[4] = start ? plaintext[4] : _0411_;
  assign _0412_ = after_xor[14] ? _0175_ : _0172_;
  assign _0413_ = ~(after_xor[15] ^ _0412_);
  assign _0004_[3] = start ? plaintext[3] : _0413_;
  assign _0414_ = plaintext[2] | ~(start);
  assign _0415_ = ~(_0184_ & after_xor[10]);
  assign _0416_ = after_xor[10] ? _0184_ : after_xor[8];
  assign _0417_ = after_xor[11] | ~(_0416_);
  assign _0418_ = _0415_ & ~(_0265_);
  assign _0419_ = ~(start | _0418_);
  assign _0420_ = ~(_0417_ & _0419_);
  assign _0004_[2] = _0414_ & _0420_;
  assign _0006_ = _0194_ ? _0069_ : _0193_;
  assign _0007_ = ~(after_xor[7] ^ _0006_);
  assign _0004_[1] = start ? plaintext[1] : _0007_;
  assign _0008_ = plaintext[0] | ~(start);
  assign _0009_ = ~(after_xor[2] & _0203_);
  assign _0010_ = after_xor[2] ? _0203_ : after_xor[0];
  assign _0011_ = after_xor[3] | ~(_0010_);
  assign _0012_ = _0009_ & ~(_0273_);
  assign _0013_ = ~(start | _0012_);
  assign _0014_ = ~(_0011_ & _0013_);
  assign _0004_[0] = _0008_ & _0014_;
  assign _0015_ = key_reg[15] & key_reg[16];
  assign _0016_ = ~(key_reg[17] & key_reg[15]);
  assign _0017_ = key_reg[17] | _0015_;
  assign _0018_ = ~(key_reg[17] ^ _0015_);
  assign _0019_ = ~(key_reg[17] | key_reg[15]);
  assign _0020_ = ~(key_reg[16] & _0019_);
  assign _0021_ = ~(key_reg[16] ^ _0019_);
  assign _0022_ = key_reg[18] ? _0021_ : _0018_;
  assign _0001_[78] = start ? key[78] : _0022_;
  assign _0023_ = key_reg[16] & _0016_;
  assign _0024_ = key_reg[18] | _0023_;
  assign _0025_ = key_reg[18] & _0016_;
  assign _0026_ = ~(_0017_ & _0025_);
  assign _0027_ = _0024_ & _0026_;
  assign _0001_[77] = start ? key[77] : _0027_;
  assign _0028_ = key_reg[15] & ~(key_reg[16]);
  assign _0029_ = ~(key_reg[15] ^ key_reg[16]);
  assign _0030_ = key_reg[17] ? _0029_ : key_reg[15];
  assign _0031_ = key_reg[18] ^ _0030_;
  assign _0001_[76] = start ? key[76] : _0031_;
  assign _0001_[75] = start ? key[75] : key_reg[14];
  assign _0001_[74] = start ? key[74] : key_reg[13];
  assign _0001_[73] = start ? key[73] : key_reg[12];
  assign _0001_[72] = start ? key[72] : key_reg[11];
  assign _0001_[71] = start ? key[71] : key_reg[10];
  assign _0001_[70] = start ? key[70] : key_reg[9];
  assign _0001_[69] = start ? key[69] : key_reg[8];
  assign _0001_[68] = start ? key[68] : key_reg[7];
  assign _0001_[67] = start ? key[67] : key_reg[6];
  assign _0001_[66] = start ? key[66] : key_reg[5];
  assign _0001_[65] = start ? key[65] : key_reg[4];
  assign _0001_[64] = start ? key[64] : key_reg[3];
  assign _0001_[63] = start ? key[63] : key_reg[2];
  assign _0001_[62] = start ? key[62] : key_reg[1];
  assign _0001_[61] = start ? key[61] : key_reg[0];
  assign _0001_[60] = start ? key[60] : key_reg[79];
  assign _0001_[59] = start ? key[59] : key_reg[78];
  assign _0001_[58] = start ? key[58] : key_reg[77];
  assign _0001_[57] = start ? key[57] : key_reg[76];
  assign _0001_[56] = start ? key[56] : key_reg[75];
  assign _0001_[55] = start ? key[55] : key_reg[74];
  assign _0001_[54] = start ? key[54] : key_reg[73];
  assign _0001_[53] = start ? key[53] : key_reg[72];
  assign _0001_[52] = start ? key[52] : key_reg[71];
  assign _0001_[51] = start ? key[51] : key_reg[70];
  assign _0001_[50] = start ? key[50] : key_reg[69];
  assign _0001_[49] = start ? key[49] : key_reg[68];
  assign _0001_[48] = start ? key[48] : key_reg[67];
  assign _0001_[47] = start ? key[47] : key_reg[66];
  assign _0001_[46] = start ? key[46] : key_reg[65];
  assign _0001_[45] = start ? key[45] : key_reg[64];
  assign _0001_[44] = start ? key[44] : key_reg[63];
  assign _0001_[43] = start ? key[43] : key_reg[62];
  assign _0001_[42] = start ? key[42] : key_reg[61];
  assign _0001_[41] = start ? key[41] : key_reg[60];
  assign _0001_[40] = start ? key[40] : key_reg[59];
  assign _0001_[39] = start ? key[39] : key_reg[58];
  assign _0001_[38] = start ? key[38] : key_reg[57];
  assign _0001_[37] = start ? key[37] : key_reg[56];
  assign _0001_[36] = start ? key[36] : key_reg[55];
  assign _0001_[35] = start ? key[35] : key_reg[54];
  assign _0001_[34] = start ? key[34] : key_reg[53];
  assign _0001_[33] = start ? key[33] : key_reg[52];
  assign _0001_[32] = start ? key[32] : key_reg[51];
  assign _0001_[31] = start ? key[31] : key_reg[50];
  assign _0001_[30] = start ? key[30] : key_reg[49];
  assign _0001_[29] = start ? key[29] : key_reg[48];
  assign _0001_[28] = start ? key[28] : key_reg[47];
  assign _0001_[27] = start ? key[27] : key_reg[46];
  assign _0001_[26] = start ? key[26] : key_reg[45];
  assign _0001_[25] = start ? key[25] : key_reg[44];
  assign _0001_[24] = start ? key[24] : key_reg[43];
  assign _0001_[23] = start ? key[23] : key_reg[42];
  assign _0001_[22] = start ? key[22] : key_reg[41];
  assign _0001_[21] = start ? key[21] : key_reg[40];
  assign _0001_[20] = start ? key[20] : key_reg[39];
  assign _0032_ = round_cnt[0] & round_cnt[1];
  assign _0033_ = round_cnt[2] & _0032_;
  assign _0034_ = round_cnt[3] & _0033_;
  assign _0035_ = ~(round_cnt[4] & _0034_);
  assign _0036_ = ~(round_cnt[4] ^ _0034_);
  assign _0037_ = ~(key_reg[38] ^ _0036_);
  assign _0001_[19] = start ? key[19] : _0037_;
  assign _0038_ = ~(round_cnt[3] ^ _0033_);
  assign _0039_ = ~(key_reg[37] ^ _0038_);
  assign _0001_[18] = start ? key[18] : _0039_;
  assign _0040_ = ~(round_cnt[2] ^ _0032_);
  assign _0041_ = ~(key_reg[36] ^ _0040_);
  assign _0001_[17] = start ? key[17] : _0041_;
  assign _0042_ = ~(round_cnt[0] ^ round_cnt[1]);
  assign _0043_ = ~(key_reg[35] ^ _0042_);
  assign _0001_[16] = start ? key[16] : _0043_;
  assign _0044_ = ~(key_reg[34] ^ round_cnt[0]);
  assign _0001_[15] = start ? key[15] : _0044_;
  assign _0001_[14] = start ? key[14] : key_reg[33];
  assign _0001_[13] = start ? key[13] : key_reg[32];
  assign _0001_[12] = start ? key[12] : key_reg[31];
  assign _0001_[11] = start ? key[11] : key_reg[30];
  assign _0001_[10] = start ? key[10] : key_reg[29];
  assign _0001_[9] = start ? key[9] : key_reg[28];
  assign _0001_[8] = start ? key[8] : key_reg[27];
  assign _0001_[7] = start ? key[7] : key_reg[26];
  assign _0001_[6] = start ? key[6] : key_reg[25];
  assign _0001_[5] = start ? key[5] : key_reg[24];
  assign _0001_[4] = start ? key[4] : key_reg[23];
  assign _0001_[3] = start ? key[3] : key_reg[22];
  assign _0001_[2] = start ? key[2] : key_reg[21];
  assign _0001_[1] = start ? key[1] : key_reg[20];
  assign _0001_[0] = start ? key[0] : key_reg[19];
  assign _0002_[3] = ~(start | _0038_);
  assign _0002_[2] = ~(start | _0040_);
  assign _0002_[1] = ~(start | _0042_);
  assign _0002_[0] = ~(start | round_cnt[0]);
  assign _0005_ = start | running;
  assign _0045_ = start | _0035_;
  assign _0003_ = _0005_ & _0045_;
  assign _0000_ = running & ~(_0045_);
  assign _0046_ = ~(_0210_ & _0374_);
  assign _0047_ = _0375_ & ~(after_xor[63]);
  assign _0048_ = _0046_ & _0047_;
  assign _0049_ = after_xor[60] | after_xor[61];
  assign _0050_ = _0210_ & after_xor[63];
  assign _0051_ = _0049_ & _0050_;
  assign _0052_ = _0048_ | _0051_;
  assign _0004_[63] = start ? plaintext[63] : _0052_;
  assign _0053_ = key_reg[15] | key_reg[16];
  assign _0054_ = key_reg[18] & ~(key_reg[17]);
  assign _0055_ = ~(_0053_ & _0054_);
  assign _0056_ = ~(key_reg[18] | _0028_);
  assign _0057_ = ~(_0020_ & _0056_);
  assign _0058_ = ~(_0055_ & _0057_);
  assign _0001_[79] = start ? key[79] : _0058_;
  assign _0002_[4] = ~(start | _0036_);
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[0] <= 1'h0;
    else if (_0003_) key_reg[0] <= _0001_[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[1] <= 1'h0;
    else if (_0003_) key_reg[1] <= _0001_[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[2] <= 1'h0;
    else if (_0003_) key_reg[2] <= _0001_[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[3] <= 1'h0;
    else if (_0003_) key_reg[3] <= _0001_[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[4] <= 1'h0;
    else if (_0003_) key_reg[4] <= _0001_[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[5] <= 1'h0;
    else if (_0003_) key_reg[5] <= _0001_[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[6] <= 1'h0;
    else if (_0003_) key_reg[6] <= _0001_[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[7] <= 1'h0;
    else if (_0003_) key_reg[7] <= _0001_[7];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[8] <= 1'h0;
    else if (_0003_) key_reg[8] <= _0001_[8];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[9] <= 1'h0;
    else if (_0003_) key_reg[9] <= _0001_[9];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[10] <= 1'h0;
    else if (_0003_) key_reg[10] <= _0001_[10];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[11] <= 1'h0;
    else if (_0003_) key_reg[11] <= _0001_[11];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[12] <= 1'h0;
    else if (_0003_) key_reg[12] <= _0001_[12];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[13] <= 1'h0;
    else if (_0003_) key_reg[13] <= _0001_[13];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[14] <= 1'h0;
    else if (_0003_) key_reg[14] <= _0001_[14];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[15] <= 1'h0;
    else if (_0003_) key_reg[15] <= _0001_[15];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[16] <= 1'h0;
    else if (_0003_) key_reg[16] <= _0001_[16];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[17] <= 1'h0;
    else if (_0003_) key_reg[17] <= _0001_[17];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[18] <= 1'h0;
    else if (_0003_) key_reg[18] <= _0001_[18];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[19] <= 1'h0;
    else if (_0003_) key_reg[19] <= _0001_[19];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[20] <= 1'h0;
    else if (_0003_) key_reg[20] <= _0001_[20];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[21] <= 1'h0;
    else if (_0003_) key_reg[21] <= _0001_[21];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[22] <= 1'h0;
    else if (_0003_) key_reg[22] <= _0001_[22];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[23] <= 1'h0;
    else if (_0003_) key_reg[23] <= _0001_[23];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[24] <= 1'h0;
    else if (_0003_) key_reg[24] <= _0001_[24];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[25] <= 1'h0;
    else if (_0003_) key_reg[25] <= _0001_[25];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[26] <= 1'h0;
    else if (_0003_) key_reg[26] <= _0001_[26];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[27] <= 1'h0;
    else if (_0003_) key_reg[27] <= _0001_[27];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[28] <= 1'h0;
    else if (_0003_) key_reg[28] <= _0001_[28];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[29] <= 1'h0;
    else if (_0003_) key_reg[29] <= _0001_[29];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[30] <= 1'h0;
    else if (_0003_) key_reg[30] <= _0001_[30];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[31] <= 1'h0;
    else if (_0003_) key_reg[31] <= _0001_[31];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[32] <= 1'h0;
    else if (_0003_) key_reg[32] <= _0001_[32];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[33] <= 1'h0;
    else if (_0003_) key_reg[33] <= _0001_[33];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[34] <= 1'h0;
    else if (_0003_) key_reg[34] <= _0001_[34];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[35] <= 1'h0;
    else if (_0003_) key_reg[35] <= _0001_[35];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[36] <= 1'h0;
    else if (_0003_) key_reg[36] <= _0001_[36];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[37] <= 1'h0;
    else if (_0003_) key_reg[37] <= _0001_[37];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[38] <= 1'h0;
    else if (_0003_) key_reg[38] <= _0001_[38];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[39] <= 1'h0;
    else if (_0003_) key_reg[39] <= _0001_[39];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[40] <= 1'h0;
    else if (_0003_) key_reg[40] <= _0001_[40];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[41] <= 1'h0;
    else if (_0003_) key_reg[41] <= _0001_[41];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[42] <= 1'h0;
    else if (_0003_) key_reg[42] <= _0001_[42];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[43] <= 1'h0;
    else if (_0003_) key_reg[43] <= _0001_[43];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[44] <= 1'h0;
    else if (_0003_) key_reg[44] <= _0001_[44];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[45] <= 1'h0;
    else if (_0003_) key_reg[45] <= _0001_[45];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[46] <= 1'h0;
    else if (_0003_) key_reg[46] <= _0001_[46];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[47] <= 1'h0;
    else if (_0003_) key_reg[47] <= _0001_[47];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[48] <= 1'h0;
    else if (_0003_) key_reg[48] <= _0001_[48];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[49] <= 1'h0;
    else if (_0003_) key_reg[49] <= _0001_[49];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[50] <= 1'h0;
    else if (_0003_) key_reg[50] <= _0001_[50];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[51] <= 1'h0;
    else if (_0003_) key_reg[51] <= _0001_[51];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[52] <= 1'h0;
    else if (_0003_) key_reg[52] <= _0001_[52];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[53] <= 1'h0;
    else if (_0003_) key_reg[53] <= _0001_[53];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[54] <= 1'h0;
    else if (_0003_) key_reg[54] <= _0001_[54];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[55] <= 1'h0;
    else if (_0003_) key_reg[55] <= _0001_[55];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[56] <= 1'h0;
    else if (_0003_) key_reg[56] <= _0001_[56];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[57] <= 1'h0;
    else if (_0003_) key_reg[57] <= _0001_[57];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[58] <= 1'h0;
    else if (_0003_) key_reg[58] <= _0001_[58];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[59] <= 1'h0;
    else if (_0003_) key_reg[59] <= _0001_[59];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[60] <= 1'h0;
    else if (_0003_) key_reg[60] <= _0001_[60];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[61] <= 1'h0;
    else if (_0003_) key_reg[61] <= _0001_[61];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[62] <= 1'h0;
    else if (_0003_) key_reg[62] <= _0001_[62];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[63] <= 1'h0;
    else if (_0003_) key_reg[63] <= _0001_[63];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[64] <= 1'h0;
    else if (_0003_) key_reg[64] <= _0001_[64];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[65] <= 1'h0;
    else if (_0003_) key_reg[65] <= _0001_[65];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[66] <= 1'h0;
    else if (_0003_) key_reg[66] <= _0001_[66];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[67] <= 1'h0;
    else if (_0003_) key_reg[67] <= _0001_[67];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[68] <= 1'h0;
    else if (_0003_) key_reg[68] <= _0001_[68];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[69] <= 1'h0;
    else if (_0003_) key_reg[69] <= _0001_[69];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[70] <= 1'h0;
    else if (_0003_) key_reg[70] <= _0001_[70];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[71] <= 1'h0;
    else if (_0003_) key_reg[71] <= _0001_[71];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[72] <= 1'h0;
    else if (_0003_) key_reg[72] <= _0001_[72];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[73] <= 1'h0;
    else if (_0003_) key_reg[73] <= _0001_[73];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[74] <= 1'h0;
    else if (_0003_) key_reg[74] <= _0001_[74];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[75] <= 1'h0;
    else if (_0003_) key_reg[75] <= _0001_[75];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[76] <= 1'h0;
    else if (_0003_) key_reg[76] <= _0001_[76];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[77] <= 1'h0;
    else if (_0003_) key_reg[77] <= _0001_[77];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[78] <= 1'h0;
    else if (_0003_) key_reg[78] <= _0001_[78];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_reg[79] <= 1'h0;
    else if (_0003_) key_reg[79] <= _0001_[79];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[0] <= 1'h0;
    else if (_0003_) state_reg[0] <= _0004_[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[1] <= 1'h0;
    else if (_0003_) state_reg[1] <= _0004_[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[2] <= 1'h0;
    else if (_0003_) state_reg[2] <= _0004_[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[3] <= 1'h0;
    else if (_0003_) state_reg[3] <= _0004_[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[4] <= 1'h0;
    else if (_0003_) state_reg[4] <= _0004_[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[5] <= 1'h0;
    else if (_0003_) state_reg[5] <= _0004_[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[6] <= 1'h0;
    else if (_0003_) state_reg[6] <= _0004_[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[7] <= 1'h0;
    else if (_0003_) state_reg[7] <= _0004_[7];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[8] <= 1'h0;
    else if (_0003_) state_reg[8] <= _0004_[8];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[9] <= 1'h0;
    else if (_0003_) state_reg[9] <= _0004_[9];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[10] <= 1'h0;
    else if (_0003_) state_reg[10] <= _0004_[10];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[11] <= 1'h0;
    else if (_0003_) state_reg[11] <= _0004_[11];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[12] <= 1'h0;
    else if (_0003_) state_reg[12] <= _0004_[12];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[13] <= 1'h0;
    else if (_0003_) state_reg[13] <= _0004_[13];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[14] <= 1'h0;
    else if (_0003_) state_reg[14] <= _0004_[14];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[15] <= 1'h0;
    else if (_0003_) state_reg[15] <= _0004_[15];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[16] <= 1'h0;
    else if (_0003_) state_reg[16] <= _0004_[16];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[17] <= 1'h0;
    else if (_0003_) state_reg[17] <= _0004_[17];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[18] <= 1'h0;
    else if (_0003_) state_reg[18] <= _0004_[18];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[19] <= 1'h0;
    else if (_0003_) state_reg[19] <= _0004_[19];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[20] <= 1'h0;
    else if (_0003_) state_reg[20] <= _0004_[20];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[21] <= 1'h0;
    else if (_0003_) state_reg[21] <= _0004_[21];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[22] <= 1'h0;
    else if (_0003_) state_reg[22] <= _0004_[22];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[23] <= 1'h0;
    else if (_0003_) state_reg[23] <= _0004_[23];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[24] <= 1'h0;
    else if (_0003_) state_reg[24] <= _0004_[24];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[25] <= 1'h0;
    else if (_0003_) state_reg[25] <= _0004_[25];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[26] <= 1'h0;
    else if (_0003_) state_reg[26] <= _0004_[26];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[27] <= 1'h0;
    else if (_0003_) state_reg[27] <= _0004_[27];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[28] <= 1'h0;
    else if (_0003_) state_reg[28] <= _0004_[28];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[29] <= 1'h0;
    else if (_0003_) state_reg[29] <= _0004_[29];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[30] <= 1'h0;
    else if (_0003_) state_reg[30] <= _0004_[30];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[31] <= 1'h0;
    else if (_0003_) state_reg[31] <= _0004_[31];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[32] <= 1'h0;
    else if (_0003_) state_reg[32] <= _0004_[32];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[33] <= 1'h0;
    else if (_0003_) state_reg[33] <= _0004_[33];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[34] <= 1'h0;
    else if (_0003_) state_reg[34] <= _0004_[34];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[35] <= 1'h0;
    else if (_0003_) state_reg[35] <= _0004_[35];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[36] <= 1'h0;
    else if (_0003_) state_reg[36] <= _0004_[36];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[37] <= 1'h0;
    else if (_0003_) state_reg[37] <= _0004_[37];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[38] <= 1'h0;
    else if (_0003_) state_reg[38] <= _0004_[38];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[39] <= 1'h0;
    else if (_0003_) state_reg[39] <= _0004_[39];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[40] <= 1'h0;
    else if (_0003_) state_reg[40] <= _0004_[40];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[41] <= 1'h0;
    else if (_0003_) state_reg[41] <= _0004_[41];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[42] <= 1'h0;
    else if (_0003_) state_reg[42] <= _0004_[42];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[43] <= 1'h0;
    else if (_0003_) state_reg[43] <= _0004_[43];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[44] <= 1'h0;
    else if (_0003_) state_reg[44] <= _0004_[44];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[45] <= 1'h0;
    else if (_0003_) state_reg[45] <= _0004_[45];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[46] <= 1'h0;
    else if (_0003_) state_reg[46] <= _0004_[46];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[47] <= 1'h0;
    else if (_0003_) state_reg[47] <= _0004_[47];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[48] <= 1'h0;
    else if (_0003_) state_reg[48] <= _0004_[48];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[49] <= 1'h0;
    else if (_0003_) state_reg[49] <= _0004_[49];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[50] <= 1'h0;
    else if (_0003_) state_reg[50] <= _0004_[50];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[51] <= 1'h0;
    else if (_0003_) state_reg[51] <= _0004_[51];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[52] <= 1'h0;
    else if (_0003_) state_reg[52] <= _0004_[52];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[53] <= 1'h0;
    else if (_0003_) state_reg[53] <= _0004_[53];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[54] <= 1'h0;
    else if (_0003_) state_reg[54] <= _0004_[54];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[55] <= 1'h0;
    else if (_0003_) state_reg[55] <= _0004_[55];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[56] <= 1'h0;
    else if (_0003_) state_reg[56] <= _0004_[56];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[57] <= 1'h0;
    else if (_0003_) state_reg[57] <= _0004_[57];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[58] <= 1'h0;
    else if (_0003_) state_reg[58] <= _0004_[58];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[59] <= 1'h0;
    else if (_0003_) state_reg[59] <= _0004_[59];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[60] <= 1'h0;
    else if (_0003_) state_reg[60] <= _0004_[60];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[61] <= 1'h0;
    else if (_0003_) state_reg[61] <= _0004_[61];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[62] <= 1'h0;
    else if (_0003_) state_reg[62] <= _0004_[62];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_reg[63] <= 1'h0;
    else if (_0003_) state_reg[63] <= _0004_[63];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) round_cnt[0] <= 1'h0;
    else if (_0005_) round_cnt[0] <= _0002_[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) round_cnt[1] <= 1'h0;
    else if (_0005_) round_cnt[1] <= _0002_[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) round_cnt[2] <= 1'h0;
    else if (_0005_) round_cnt[2] <= _0002_[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) round_cnt[3] <= 1'h0;
    else if (_0005_) round_cnt[3] <= _0002_[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) round_cnt[4] <= 1'h0;
    else if (_0005_) round_cnt[4] <= _0002_[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[0] <= 1'h0;
    else if (_0000_) ciphertext[0] <= after_xor[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[1] <= 1'h0;
    else if (_0000_) ciphertext[1] <= after_xor[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[2] <= 1'h0;
    else if (_0000_) ciphertext[2] <= after_xor[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[3] <= 1'h0;
    else if (_0000_) ciphertext[3] <= after_xor[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[4] <= 1'h0;
    else if (_0000_) ciphertext[4] <= after_xor[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[5] <= 1'h0;
    else if (_0000_) ciphertext[5] <= after_xor[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[6] <= 1'h0;
    else if (_0000_) ciphertext[6] <= after_xor[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[7] <= 1'h0;
    else if (_0000_) ciphertext[7] <= after_xor[7];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[8] <= 1'h0;
    else if (_0000_) ciphertext[8] <= after_xor[8];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[9] <= 1'h0;
    else if (_0000_) ciphertext[9] <= after_xor[9];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[10] <= 1'h0;
    else if (_0000_) ciphertext[10] <= after_xor[10];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[11] <= 1'h0;
    else if (_0000_) ciphertext[11] <= after_xor[11];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[12] <= 1'h0;
    else if (_0000_) ciphertext[12] <= after_xor[12];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[13] <= 1'h0;
    else if (_0000_) ciphertext[13] <= after_xor[13];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[14] <= 1'h0;
    else if (_0000_) ciphertext[14] <= after_xor[14];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[15] <= 1'h0;
    else if (_0000_) ciphertext[15] <= after_xor[15];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[16] <= 1'h0;
    else if (_0000_) ciphertext[16] <= after_xor[16];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[17] <= 1'h0;
    else if (_0000_) ciphertext[17] <= after_xor[17];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[18] <= 1'h0;
    else if (_0000_) ciphertext[18] <= after_xor[18];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[19] <= 1'h0;
    else if (_0000_) ciphertext[19] <= after_xor[19];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[20] <= 1'h0;
    else if (_0000_) ciphertext[20] <= after_xor[20];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[21] <= 1'h0;
    else if (_0000_) ciphertext[21] <= after_xor[21];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[22] <= 1'h0;
    else if (_0000_) ciphertext[22] <= after_xor[22];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[23] <= 1'h0;
    else if (_0000_) ciphertext[23] <= after_xor[23];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[24] <= 1'h0;
    else if (_0000_) ciphertext[24] <= after_xor[24];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[25] <= 1'h0;
    else if (_0000_) ciphertext[25] <= after_xor[25];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[26] <= 1'h0;
    else if (_0000_) ciphertext[26] <= after_xor[26];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[27] <= 1'h0;
    else if (_0000_) ciphertext[27] <= after_xor[27];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[28] <= 1'h0;
    else if (_0000_) ciphertext[28] <= after_xor[28];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[29] <= 1'h0;
    else if (_0000_) ciphertext[29] <= after_xor[29];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[30] <= 1'h0;
    else if (_0000_) ciphertext[30] <= after_xor[30];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[31] <= 1'h0;
    else if (_0000_) ciphertext[31] <= after_xor[31];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[32] <= 1'h0;
    else if (_0000_) ciphertext[32] <= after_xor[32];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[33] <= 1'h0;
    else if (_0000_) ciphertext[33] <= after_xor[33];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[34] <= 1'h0;
    else if (_0000_) ciphertext[34] <= after_xor[34];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[35] <= 1'h0;
    else if (_0000_) ciphertext[35] <= after_xor[35];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[36] <= 1'h0;
    else if (_0000_) ciphertext[36] <= after_xor[36];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[37] <= 1'h0;
    else if (_0000_) ciphertext[37] <= after_xor[37];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[38] <= 1'h0;
    else if (_0000_) ciphertext[38] <= after_xor[38];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[39] <= 1'h0;
    else if (_0000_) ciphertext[39] <= after_xor[39];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[40] <= 1'h0;
    else if (_0000_) ciphertext[40] <= after_xor[40];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[41] <= 1'h0;
    else if (_0000_) ciphertext[41] <= after_xor[41];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[42] <= 1'h0;
    else if (_0000_) ciphertext[42] <= after_xor[42];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[43] <= 1'h0;
    else if (_0000_) ciphertext[43] <= after_xor[43];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[44] <= 1'h0;
    else if (_0000_) ciphertext[44] <= after_xor[44];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[45] <= 1'h0;
    else if (_0000_) ciphertext[45] <= after_xor[45];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[46] <= 1'h0;
    else if (_0000_) ciphertext[46] <= after_xor[46];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[47] <= 1'h0;
    else if (_0000_) ciphertext[47] <= after_xor[47];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[48] <= 1'h0;
    else if (_0000_) ciphertext[48] <= after_xor[48];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[49] <= 1'h0;
    else if (_0000_) ciphertext[49] <= after_xor[49];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[50] <= 1'h0;
    else if (_0000_) ciphertext[50] <= after_xor[50];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[51] <= 1'h0;
    else if (_0000_) ciphertext[51] <= after_xor[51];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[52] <= 1'h0;
    else if (_0000_) ciphertext[52] <= after_xor[52];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[53] <= 1'h0;
    else if (_0000_) ciphertext[53] <= after_xor[53];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[54] <= 1'h0;
    else if (_0000_) ciphertext[54] <= after_xor[54];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[55] <= 1'h0;
    else if (_0000_) ciphertext[55] <= after_xor[55];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[56] <= 1'h0;
    else if (_0000_) ciphertext[56] <= after_xor[56];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[57] <= 1'h0;
    else if (_0000_) ciphertext[57] <= after_xor[57];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[58] <= 1'h0;
    else if (_0000_) ciphertext[58] <= after_xor[58];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[59] <= 1'h0;
    else if (_0000_) ciphertext[59] <= after_xor[59];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[60] <= 1'h0;
    else if (_0000_) ciphertext[60] <= after_xor[60];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[61] <= 1'h0;
    else if (_0000_) ciphertext[61] <= after_xor[61];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[62] <= 1'h0;
    else if (_0000_) ciphertext[62] <= after_xor[62];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ciphertext[63] <= 1'h0;
    else if (_0000_) ciphertext[63] <= after_xor[63];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) done <= 1'h0;
    else done <= _0000_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) running <= 1'h0;
    else running <= _0003_;
  assign \sbox$func$present80.v:87$25.x  = 4'hx;
  assign \keySchedule$func$present80.v:121$24.s_out  = 4'hx;
  assign \keySchedule$func$present80.v:121$24.k1  = 80'hxxxxxxxxxxxxxxxxxxxx;
  assign \keySchedule$func$present80.v:121$24.round_cnt  = 5'hxx;
  assign \keySchedule$func$present80.v:121$24.k  = 80'hxxxxxxxxxxxxxxxxxxxx;
  assign \pLayer$func$present80.v:118$23.result  = 64'hxxxxxxxxxxxxxxxx;
  assign \pLayer$func$present80.v:118$23.i  = 32'hxxxxxxxx;
  assign \pLayer$func$present80.v:118$23.state  = 64'hxxxxxxxxxxxxxxxx;
  assign \sbox$func$present80.v:51$22.x  = 4'hx;
  assign \sbox$func$present80.v:51$21.x  = 4'hx;
  assign \sbox$func$present80.v:51$20.x  = 4'hx;
  assign \sbox$func$present80.v:51$19.x  = 4'hx;
  assign \sbox$func$present80.v:51$18.x  = 4'hx;
  assign \sbox$func$present80.v:51$17.x  = 4'hx;
  assign \sbox$func$present80.v:51$16.x  = 4'hx;
  assign \sbox$func$present80.v:51$15.x  = 4'hx;
  assign \sbox$func$present80.v:51$14.x  = 4'hx;
  assign \sbox$func$present80.v:51$13.x  = 4'hx;
  assign \sbox$func$present80.v:51$12.x  = 4'hx;
  assign \sbox$func$present80.v:51$11.x  = 4'hx;
  assign \sbox$func$present80.v:51$10.x  = 4'hx;
  assign \sbox$func$present80.v:51$9.x  = 4'hx;
  assign \sbox$func$present80.v:51$8.x  = 4'hx;
  assign \sbox$func$present80.v:51$7.x  = 4'hx;
  assign \sLayer$func$present80.v:115$6.result  = 64'hxxxxxxxxxxxxxxxx;
  assign \sLayer$func$present80.v:115$6.i  = 32'hxxxxxxxx;
  assign \sLayer$func$present80.v:115$6.state  = 64'hxxxxxxxxxxxxxxxx;
  assign { next_key[75:20], next_key[14:0] } = { key_reg[14:0], key_reg[79:39], key_reg[33:19] };
endmodule
