"""Ground-truth vector testbench for present80 (generated by vector_tb).

Loads each spec test vector MSB-first over the serial interface, waits
(bounded) for the completion port, unloads the result, and asserts it equals
the spec's published value. Emits ``VEC|...`` on mismatch.
"""
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, Timer

INPUT_BITS = (80, 64)
OUTPUT_BITS = 64
MAX_WAIT = 656
# (input_a, input_b, expected_output)
VECTORS = [(0, 0, 6159166413734052933), (1208925819614629174706175, 0, 16657766916304425033), (0, 18446744073709551615, 11606620420646125947), (1208925819614629174706175, 18446744073709551615, 3689535319099707602)]


async def _shift_in(dut, value, nbits):
    for i in range(nbits - 1, -1, -1):          # MSB-first
        await FallingEdge(dut.clk)
        dut.load_en.value = 1
        dut.din.value = (value >> i) & 1


@cocotb.test()
async def test_present80_vectors(dut):
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())
    for vec in VECTORS:
        inputs, exp = vec[:-1], vec[-1]
        # reset
        dut.rst_n.value = 0
        dut.load_en.value = 0
        dut.din.value = 0
        dut.shift_out_en.value = 0
        await RisingEdge(dut.clk)
        await RisingEdge(dut.clk)
        dut.rst_n.value = 1

        # load each input field MSB-first, in table order
        for value, nbits in zip(inputs, INPUT_BITS):
            await _shift_in(dut, value, nbits)
        await FallingEdge(dut.clk)
        dut.load_en.value = 0
        dut.din.value = 0

        # wait (bounded) for completion
        waited = 0
        while int(dut.done.value) == 0 and waited < MAX_WAIT:
            await RisingEdge(dut.clk)
            waited += 1
        assert int(dut.done.value) == 1, (
            f"VEC|inputs={[hex(v) for v in inputs]}|signal=done|"
            f"expected=1|actual=0 (never asserted within {MAX_WAIT} cycles)"
        )

        # unload the result MSB-first
        result = 0
        for _ in range(OUTPUT_BITS):
            await FallingEdge(dut.clk)
            dut.shift_out_en.value = 1
            await Timer(1, units="ns")
            result = (result << 1) | (int(dut.dout.value) & 1)
            await RisingEdge(dut.clk)
        dut.shift_out_en.value = 0

        assert result == exp, (
            f"VEC|inputs={[hex(v) for v in inputs]}|signal=output|"
            f"expected={exp:0{OUTPUT_BITS // 4}x}|actual={result:0{OUTPUT_BITS // 4}x}"
        )
