/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module spi_slave_regs(clk, rst_n, sclk, cs_n, mosi, miso, done);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input sclk;
  wire sclk;
  input cs_n;
  wire cs_n;
  input mosi;
  wire mosi;
  output miso;
  reg miso;
  output done;
  reg done;
  wire [4:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  reg [6:0] addr_lat;
  reg [4:0] bit_cnt;
  wire [7:0] cmd_byte;
  wire cs_assert;
  reg [2:0] cs_sync;
  reg [7:0] ctrl_reg;
  wire [7:0] data_byte;
  reg frame_active;
  wire mosi_s;
  reg [1:0] mosi_sync;
  reg rw_lat;
  reg [2:0] sclk_sync;
  reg [7:0] scr0_reg;
  reg [7:0] scr1_reg;
  reg [7:0] scr2_reg;
  reg [7:0] scr3_reg;
  reg [6:0] shift_in;
  wire [7:0] shift_out;
  assign _153_ = bit_cnt[1] & bit_cnt[0];
  assign _154_ = bit_cnt[2] & _153_;
  assign _155_ = bit_cnt[3] | _154_;
  assign _156_ = ~(bit_cnt[3] & _154_);
  assign _157_ = cs_sync[2] | ~(cs_sync[1]);
  assign _158_ = cs_sync[1] | ~(cs_sync[2]);
  assign cs_assert = ~_158_;
  assign _015_ = _157_ & _158_;
  assign _003_ = ~_015_;
  assign _016_ = _155_ & _015_;
  assign _000_[3] = _156_ & _016_;
  assign _017_ = bit_cnt[2] | _153_;
  assign _018_ = _015_ & _017_;
  assign _000_[2] = _018_ & ~(_154_);
  assign _019_ = ~(bit_cnt[1] | bit_cnt[0]);
  assign _020_ = ~(_153_ | _019_);
  assign _000_[1] = _015_ & _020_;
  assign _000_[0] = _015_ & ~(bit_cnt[0]);
  assign _021_ = _019_ & ~(bit_cnt[2]);
  assign _022_ = bit_cnt[3] & ~(bit_cnt[4]);
  assign _023_ = _021_ & _022_;
  assign _024_ = shift_out[5] | _023_;
  assign _025_ = ~(addr_lat[2] | addr_lat[3]);
  assign _026_ = _025_ & ~(addr_lat[0]);
  assign _027_ = addr_lat[1] & _026_;
  assign _028_ = ~(addr_lat[6] | addr_lat[5]);
  assign _029_ = _028_ & ~(addr_lat[4]);
  assign _030_ = _027_ & _029_;
  assign _031_ = ~(ctrl_reg[5] & _030_);
  assign _032_ = addr_lat[4] & _028_;
  assign _033_ = _026_ & ~(addr_lat[1]);
  assign _034_ = _032_ & _033_;
  assign _035_ = ~(scr0_reg[5] & _034_);
  assign _036_ = _027_ & _032_;
  assign _037_ = ~(scr2_reg[5] & _036_);
  assign _038_ = _035_ & _037_;
  assign _039_ = addr_lat[0] & _025_;
  assign _040_ = addr_lat[1] & _039_;
  assign _041_ = _032_ & _040_;
  assign _042_ = ~(scr3_reg[5] & _041_);
  assign _043_ = _039_ & ~(addr_lat[1]);
  assign _044_ = _032_ & _043_;
  assign _045_ = ~(scr1_reg[5] & _044_);
  assign _046_ = _023_ & _042_;
  assign _047_ = _031_ & _045_;
  assign _048_ = _038_ & _047_;
  assign _049_ = ~(_046_ & _048_);
  assign _164_ = _024_ & _049_;
  assign _050_ = shift_out[4] | _023_;
  assign _051_ = ~(ctrl_reg[4] & _030_);
  assign _052_ = ~(_029_ & _033_);
  assign _053_ = _023_ & _052_;
  assign _054_ = ~(scr2_reg[4] & _036_);
  assign _055_ = ~(scr3_reg[4] & _041_);
  assign _056_ = ~(scr0_reg[4] & _034_);
  assign _057_ = ~(scr1_reg[4] & _044_);
  assign _058_ = _053_ & _057_;
  assign _059_ = _054_ & _056_;
  assign _060_ = _051_ & _055_;
  assign _061_ = _059_ & _060_;
  assign _062_ = ~(_058_ & _061_);
  assign _163_ = _050_ & _062_;
  assign _063_ = shift_out[3] | _023_;
  assign _064_ = ~(ctrl_reg[3] & _030_);
  assign _065_ = ~(scr2_reg[3] & _036_);
  assign _066_ = ~(scr1_reg[3] & _044_);
  assign _067_ = _065_ & _066_;
  assign _068_ = ~(scr0_reg[3] & _034_);
  assign _069_ = ~(scr3_reg[3] & _041_);
  assign _070_ = _064_ & _069_;
  assign _071_ = _053_ & _068_;
  assign _072_ = _070_ & _071_;
  assign _073_ = ~(_067_ & _072_);
  assign _162_ = _063_ & _073_;
  assign _074_ = ~(ctrl_reg[2] & _030_);
  assign _075_ = _023_ & _074_;
  assign _076_ = ~(scr0_reg[2] & _034_);
  assign _077_ = ~(scr1_reg[2] & _044_);
  assign _078_ = _076_ & _077_;
  assign _079_ = ~(scr2_reg[2] & _036_);
  assign _080_ = ~(scr3_reg[2] & _041_);
  assign _081_ = _079_ & _080_;
  assign _082_ = _078_ & _081_;
  assign _083_ = ~(_075_ & _082_);
  assign _084_ = shift_out[2] | _023_;
  assign _161_ = _083_ & _084_;
  assign _085_ = shift_out[1] | _023_;
  assign _086_ = ~(scr1_reg[1] & _044_);
  assign _087_ = _053_ & _086_;
  assign _088_ = ~(scr0_reg[1] & _034_);
  assign _089_ = ~(scr2_reg[1] & _036_);
  assign _090_ = _088_ & _089_;
  assign _091_ = ~(scr3_reg[1] & _041_);
  assign _092_ = ~(ctrl_reg[1] & _030_);
  assign _093_ = _091_ & _092_;
  assign _094_ = _090_ & _093_;
  assign _095_ = ~(_087_ & _094_);
  assign _160_ = _085_ & _095_;
  assign _096_ = ~(scr3_reg[0] & _041_);
  assign _097_ = ~(scr1_reg[0] & _044_);
  assign _098_ = ~(scr0_reg[0] & _034_);
  assign _099_ = ~(scr2_reg[0] & _036_);
  assign _100_ = ~(ctrl_reg[0] & _030_);
  assign _101_ = _096_ & _100_;
  assign _102_ = _097_ & _098_;
  assign _103_ = ~(_029_ & _043_);
  assign _104_ = _099_ & _103_;
  assign _105_ = _102_ & _104_;
  assign _106_ = ~(_101_ & _105_);
  assign _159_ = _023_ & _106_;
  assign _107_ = sclk_sync[1] & ~(sclk_sync[2]);
  assign _108_ = frame_active & _107_;
  assign _109_ = _157_ & _108_;
  assign _005_ = _015_ & _108_;
  assign _110_ = shift_out[6] | _023_;
  assign _111_ = ~(scr1_reg[6] & _044_);
  assign _112_ = _053_ & _111_;
  assign _113_ = ~(scr0_reg[6] & _034_);
  assign _114_ = ~(scr2_reg[6] & _036_);
  assign _115_ = _113_ & _114_;
  assign _116_ = ~(scr3_reg[6] & _041_);
  assign _117_ = ~(ctrl_reg[6] & _030_);
  assign _118_ = _116_ & _117_;
  assign _119_ = _115_ & _118_;
  assign _120_ = ~(_112_ & _119_);
  assign _165_ = _110_ & _120_;
  assign _121_ = ~(bit_cnt[4] | bit_cnt[3]);
  assign _122_ = bit_cnt[4] | bit_cnt[3];
  assign _123_ = _154_ & _121_;
  assign _004_ = _005_ & _123_;
  assign _124_ = ~(bit_cnt[4] | _156_);
  assign _125_ = rw_lat & _124_;
  assign _126_ = _041_ & _005_;
  assign _006_ = _125_ & _126_;
  assign _127_ = ~(ctrl_reg[7] & _030_);
  assign _128_ = ~(scr2_reg[7] & _036_);
  assign _129_ = ~(scr3_reg[7] & _041_);
  assign _130_ = ~(scr0_reg[7] & _034_);
  assign _131_ = ~(scr1_reg[7] & _044_);
  assign _132_ = _128_ & _131_;
  assign _133_ = _127_ & _129_;
  assign _134_ = _023_ & _130_;
  assign _135_ = _133_ & _134_;
  assign _136_ = ~(_132_ & _135_);
  assign _137_ = _015_ & ~(rw_lat);
  assign _138_ = shift_out[7] & _122_;
  assign _139_ = _023_ | _138_;
  assign _140_ = _137_ & _139_;
  assign _002_ = _136_ & _140_;
  assign _141_ = _036_ & _005_;
  assign _007_ = _125_ & _141_;
  assign _008_ = _108_ | ~(_015_);
  assign _142_ = _044_ & _005_;
  assign _009_ = _125_ & _142_;
  assign _143_ = sclk_sync[2] & ~(sclk_sync[1]);
  assign _144_ = ~(frame_active & _143_);
  assign _010_ = ~(_015_ & _144_);
  assign _001_ = _158_ & _124_;
  assign _145_ = bit_cnt[4] & _015_;
  assign _000_[4] = _156_ & _145_;
  assign _146_ = _137_ & ~(_144_);
  assign _011_ = _122_ & _146_;
  assign _147_ = _030_ & _005_;
  assign _012_ = _125_ & _147_;
  assign _148_ = done & _121_;
  assign _149_ = _021_ & _148_;
  assign _150_ = _124_ | _149_;
  assign _151_ = ~(_109_ & _150_);
  assign _013_ = ~(_158_ & _151_);
  assign _152_ = _034_ & _005_;
  assign _014_ = _125_ & _152_;
  reg \shift_out_reg[1] ;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \shift_out_reg[1]  <= 1'h0;
    else if (_011_) \shift_out_reg[1]  <= _159_;
  assign shift_out[1] = \shift_out_reg[1] ;
  reg \shift_out_reg[2] ;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \shift_out_reg[2]  <= 1'h0;
    else if (_011_) \shift_out_reg[2]  <= _160_;
  assign shift_out[2] = \shift_out_reg[2] ;
  reg \shift_out_reg[3] ;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \shift_out_reg[3]  <= 1'h0;
    else if (_011_) \shift_out_reg[3]  <= _161_;
  assign shift_out[3] = \shift_out_reg[3] ;
  reg \shift_out_reg[4] ;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \shift_out_reg[4]  <= 1'h0;
    else if (_011_) \shift_out_reg[4]  <= _162_;
  assign shift_out[4] = \shift_out_reg[4] ;
  reg \shift_out_reg[5] ;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \shift_out_reg[5]  <= 1'h0;
    else if (_011_) \shift_out_reg[5]  <= _163_;
  assign shift_out[5] = \shift_out_reg[5] ;
  reg \shift_out_reg[6] ;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \shift_out_reg[6]  <= 1'h0;
    else if (_011_) \shift_out_reg[6]  <= _164_;
  assign shift_out[6] = \shift_out_reg[6] ;
  reg \shift_out_reg[7] ;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \shift_out_reg[7]  <= 1'h0;
    else if (_011_) \shift_out_reg[7]  <= _165_;
  assign shift_out[7] = \shift_out_reg[7] ;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) frame_active <= 1'h0;
    else if (_003_) frame_active <= cs_assert;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr0_reg[0] <= 1'h0;
    else if (_014_) scr0_reg[0] <= mosi_sync[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr0_reg[1] <= 1'h0;
    else if (_014_) scr0_reg[1] <= shift_in[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr0_reg[2] <= 1'h0;
    else if (_014_) scr0_reg[2] <= shift_in[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr0_reg[3] <= 1'h0;
    else if (_014_) scr0_reg[3] <= shift_in[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr0_reg[4] <= 1'h0;
    else if (_014_) scr0_reg[4] <= shift_in[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr0_reg[5] <= 1'h0;
    else if (_014_) scr0_reg[5] <= shift_in[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr0_reg[6] <= 1'h0;
    else if (_014_) scr0_reg[6] <= shift_in[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr0_reg[7] <= 1'h0;
    else if (_014_) scr0_reg[7] <= shift_in[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) done <= 1'h0;
    else if (_013_) done <= _001_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg[0] <= 1'h0;
    else if (_012_) ctrl_reg[0] <= mosi_sync[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg[1] <= 1'h0;
    else if (_012_) ctrl_reg[1] <= shift_in[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg[2] <= 1'h0;
    else if (_012_) ctrl_reg[2] <= shift_in[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg[3] <= 1'h0;
    else if (_012_) ctrl_reg[3] <= shift_in[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg[4] <= 1'h0;
    else if (_012_) ctrl_reg[4] <= shift_in[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg[5] <= 1'h0;
    else if (_012_) ctrl_reg[5] <= shift_in[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg[6] <= 1'h0;
    else if (_012_) ctrl_reg[6] <= shift_in[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg[7] <= 1'h0;
    else if (_012_) ctrl_reg[7] <= shift_in[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) miso <= 1'h0;
    else if (_010_) miso <= _002_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr1_reg[0] <= 1'h0;
    else if (_009_) scr1_reg[0] <= mosi_sync[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr1_reg[1] <= 1'h0;
    else if (_009_) scr1_reg[1] <= shift_in[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr1_reg[2] <= 1'h0;
    else if (_009_) scr1_reg[2] <= shift_in[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr1_reg[3] <= 1'h0;
    else if (_009_) scr1_reg[3] <= shift_in[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr1_reg[4] <= 1'h0;
    else if (_009_) scr1_reg[4] <= shift_in[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr1_reg[5] <= 1'h0;
    else if (_009_) scr1_reg[5] <= shift_in[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr1_reg[6] <= 1'h0;
    else if (_009_) scr1_reg[6] <= shift_in[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr1_reg[7] <= 1'h0;
    else if (_009_) scr1_reg[7] <= shift_in[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) addr_lat[0] <= 1'h0;
    else if (_004_) addr_lat[0] <= mosi_sync[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) addr_lat[1] <= 1'h0;
    else if (_004_) addr_lat[1] <= shift_in[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) addr_lat[2] <= 1'h0;
    else if (_004_) addr_lat[2] <= shift_in[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) addr_lat[3] <= 1'h0;
    else if (_004_) addr_lat[3] <= shift_in[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) addr_lat[4] <= 1'h0;
    else if (_004_) addr_lat[4] <= shift_in[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) addr_lat[5] <= 1'h0;
    else if (_004_) addr_lat[5] <= shift_in[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) addr_lat[6] <= 1'h0;
    else if (_004_) addr_lat[6] <= shift_in[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) bit_cnt[0] <= 1'h0;
    else if (_008_) bit_cnt[0] <= _000_[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) bit_cnt[1] <= 1'h0;
    else if (_008_) bit_cnt[1] <= _000_[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) bit_cnt[2] <= 1'h0;
    else if (_008_) bit_cnt[2] <= _000_[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) bit_cnt[3] <= 1'h0;
    else if (_008_) bit_cnt[3] <= _000_[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) bit_cnt[4] <= 1'h0;
    else if (_008_) bit_cnt[4] <= _000_[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr2_reg[0] <= 1'h0;
    else if (_007_) scr2_reg[0] <= mosi_sync[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr2_reg[1] <= 1'h0;
    else if (_007_) scr2_reg[1] <= shift_in[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr2_reg[2] <= 1'h0;
    else if (_007_) scr2_reg[2] <= shift_in[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr2_reg[3] <= 1'h0;
    else if (_007_) scr2_reg[3] <= shift_in[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr2_reg[4] <= 1'h0;
    else if (_007_) scr2_reg[4] <= shift_in[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr2_reg[5] <= 1'h0;
    else if (_007_) scr2_reg[5] <= shift_in[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr2_reg[6] <= 1'h0;
    else if (_007_) scr2_reg[6] <= shift_in[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr2_reg[7] <= 1'h0;
    else if (_007_) scr2_reg[7] <= shift_in[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr3_reg[0] <= 1'h0;
    else if (_006_) scr3_reg[0] <= mosi_sync[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr3_reg[1] <= 1'h0;
    else if (_006_) scr3_reg[1] <= shift_in[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr3_reg[2] <= 1'h0;
    else if (_006_) scr3_reg[2] <= shift_in[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr3_reg[3] <= 1'h0;
    else if (_006_) scr3_reg[3] <= shift_in[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr3_reg[4] <= 1'h0;
    else if (_006_) scr3_reg[4] <= shift_in[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr3_reg[5] <= 1'h0;
    else if (_006_) scr3_reg[5] <= shift_in[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr3_reg[6] <= 1'h0;
    else if (_006_) scr3_reg[6] <= shift_in[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) scr3_reg[7] <= 1'h0;
    else if (_006_) scr3_reg[7] <= shift_in[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) shift_in[0] <= 1'h0;
    else if (_005_) shift_in[0] <= mosi_sync[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) shift_in[1] <= 1'h0;
    else if (_005_) shift_in[1] <= shift_in[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) shift_in[2] <= 1'h0;
    else if (_005_) shift_in[2] <= shift_in[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) shift_in[3] <= 1'h0;
    else if (_005_) shift_in[3] <= shift_in[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) shift_in[4] <= 1'h0;
    else if (_005_) shift_in[4] <= shift_in[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) shift_in[5] <= 1'h0;
    else if (_005_) shift_in[5] <= shift_in[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) shift_in[6] <= 1'h0;
    else if (_005_) shift_in[6] <= shift_in[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rw_lat <= 1'h0;
    else if (_004_) rw_lat <= shift_in[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sclk_sync[0] <= 1'h0;
    else sclk_sync[0] <= sclk;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sclk_sync[1] <= 1'h0;
    else sclk_sync[1] <= sclk_sync[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sclk_sync[2] <= 1'h0;
    else sclk_sync[2] <= sclk_sync[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cs_sync[0] <= 1'h1;
    else cs_sync[0] <= cs_n;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cs_sync[1] <= 1'h1;
    else cs_sync[1] <= cs_sync[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cs_sync[2] <= 1'h1;
    else cs_sync[2] <= cs_sync[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mosi_sync[0] <= 1'h0;
    else mosi_sync[0] <= mosi;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mosi_sync[1] <= 1'h0;
    else mosi_sync[1] <= mosi_sync[0];
  assign data_byte = { shift_in, mosi_sync[1] };
  assign cmd_byte = { shift_in, mosi_sync[1] };
  assign shift_out[0] = 1'h0;
  assign mosi_s = mosi_sync[1];
endmodule
